# Install

In [ ]:
!pip3 install pshmodule

In [ ]:
!pip3 install pickle5

In [ ]:
!pip3 install pandas==1.5.0

In [ ]:
!pip3 install swifter

In [ ]:
!pip3 install openai

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Data Load

In [7]:
import sys
sys.path.append('/content/drive/MyDrive/Advertising_By_Personality/src/business_model')
print(sys.path)

['/content', '/env/python', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.10/dist-packages/IPython/extensions', '/root/.ipython', '/content/drive/MyDrive/Advertising_By_Personality/src/business_model']

In [8]:
import swifter
import config as cfg
import pandas as pd
from tqdm import tqdm
from pshmodule.utils import filemanager as fm

In [9]:
df = fm.load(cfg.origin_data)

extension : .xlsx
Loaded 25000 records from /content/drive/MyDrive/Advertising_By_Personality/data/origin/origin.xlsx

In [10]:
df.head()

,관리번호,광고 구분,마케팅전략,일상정보,시즌정보,분류,제목,본문,납품차수
0,1,NaN,NaN,NaN,NaN,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰,"마지막 2일! [계절밥상 디너/주말 1만원, 런치 5천원 할인 쿠폰] 9월30일까지...",NaN
1,1,할인/쿠폰/혜택,"매력적인숫자(시간,돈)",NaN,NaN,ST,★최대 1만원★ 계절밥상 할인쿠폰,"이.틀.만! VIP 고객 디너&주말 1만원, 런치 5천원 할인 쿠폰 놓치지 마세요!",1차
2,1,할인/쿠폰/혜택,핵심정보만 전달,NaN,NaN,SF,ONLY VIP! 할인쿠폰♬,소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상] 디너/주말 1만원+런치 5천...,1차
3,1,할인/쿠폰/혜택,호기심유발(질문),NaN,NaN,NT,이 혜택💰 놓치지 않을 거예요,"[계절밥상] 디너/주말 1O,OOO원, 런치 5,OOO원 할인\\9월 30일까지🚨",1차
4,1,할인/쿠폰/혜택,호기심유발(이모지),NaN,NaN,NF,VIP님들만을 위한 쿠폰 도착💌,계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/주말 할인 쿠폰(~9/30) 사용하...,1차

# ChatGPT Test

In [11]:
import openai

In [16]:
# 발급받은 API 키 설정
OPENAI_API_KEY = "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"

# openai API 키 인증
openai.api_key = OPENAI_API_KEY
model = "gpt-4"

In [25]:
def generate_response(messages):
  response = openai.ChatCompletion.create(
      model=model,
      messages=messages
  )
  return response['choices'][0]['message']['content']

In [26]:
# test
df_test = df.iloc[:5]

In [28]:
title = []
content = []

for i in tqdm(df_test.iterrows()):
  # 제목 키워드 추출
  query = i[1]['제목']

  messages = [
          {"role": "system", "content": "You are a helper who extracts keywords."},
          {"role": "user", "content": f"{query}\n 위 문장에서 키워드를 추출해줘"}
  ]

  # ChatGPT API 호출하기
  title.append(generate_response(messages))

  # 본문 키워드 추출
  query = i[1]['본문']

  messages = [
          {"role": "system", "content": "You are a helper who extracts keywords."},
          {"role": "user", "content": f"{query}\n 위 문장에서 키워드를 추출해줘"}
  ]

  # ChatGPT API 호출하기
  content.append(generate_response(messages))

5it [01:00, 12.01s/it]

In [30]:
df_test['title_keyword'] = title
df_test['content_keyword'] = content

<ipython-input-30-8c3c8e6aad52>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['title_keyword'] = title
<ipython-input-30-8c3c8e6aad52>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['content_keyword'] = content

In [31]:
df_test.head()

,관리번호,광고 구분,마케팅전략,일상정보,시즌정보,분류,제목,본문,납품차수,title_keyword,content_keyword
0,1,NaN,NaN,NaN,NaN,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰,"마지막 2일! [계절밥상 디너/주말 1만원, 런치 5천원 할인 쿠폰] 9월30일까지...",NaN,"CJONE, VIP, 계절밥상, 1만원, 5천원, 할인쿠폰","마지막 2일, 계절밥상 디너, 주말, 1만원, 런치, 5천원, 할인 쿠폰, 9월30..."
1,1,할인/쿠폰/혜택,"매력적인숫자(시간,돈)",NaN,NaN,ST,★최대 1만원★ 계절밥상 할인쿠폰,"이.틀.만! VIP 고객 디너&주말 1만원, 런치 5천원 할인 쿠폰 놓치지 마세요!",1차,"최대, 1만원, 계절밥상, 할인쿠폰","VIP 고객, 디너, 주말, 1만원, 런치, 5천원, 할인 쿠폰"
2,1,할인/쿠폰/혜택,핵심정보만 전달,NaN,NaN,SF,ONLY VIP! 할인쿠폰♬,소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상] 디너/주말 1만원+런치 5천...,1차,"VIP, 할인쿠폰","소중한 이들, 든든하게, 먹다, 계절밥상, 디너, 주말, 1만원, 런치, 5천원, ..."
3,1,할인/쿠폰/혜택,호기심유발(질문),NaN,NaN,NT,이 혜택💰 놓치지 않을 거예요,"[계절밥상] 디너/주말 1O,OOO원, 런치 5,OOO원 할인\\9월 30일까지🚨",1차,혜택,"계절밥상, 디너, 주말, 1O,OOO원, 런치, 5,OOO원, 할인, 9월 30일"
4,1,할인/쿠폰/혜택,호기심유발(이모지),NaN,NaN,NF,VIP님들만을 위한 쿠폰 도착💌,계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/주말 할인 쿠폰(~9/30) 사용하...,1차,"VIP, 쿠폰, 도착","계절밥상, 든든한 한끼, 🍱, 런치, 디너, 주말 할인 쿠폰, 9/30, 소중한 사..."