# Install

In [ ]:
!pip3 install pshmodule

In [ ]:
!pip3 install pickle5

In [ ]:
!pip3 install pandas==1.5.0

In [ ]:
!pip3 install swifter

In [ ]:
!pip3 install openai

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Data Load

In [7]:
import sys
sys.path.append('/content/drive/MyDrive/Advertising_By_Personality/src/business_model/keyword_extraction')
print(sys.path)

['/content', '/env/python', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.10/dist-packages/IPython/extensions', '/root/.ipython', '/content/drive/MyDrive/Advertising_By_Personality/src/business_model/keyword_extraction']

In [8]:
import swifter
import config as cfg
import pandas as pd
from tqdm import tqdm
from pshmodule.utils import filemanager as fm

In [9]:
# df = fm.load("/content/drive/MyDrive/Advertising_By_Personality/data/reports/test.xlsx")
df = fm.load(cfg.origin_data)

extension : .xlsx
Loaded 24980 records from /content/drive/MyDrive/Advertising_By_Personality/data/origin/origin.xlsx

이름 변경

In [10]:
df.rename(columns={'관리번호':'no', '광고 구분':'advertisement_type', '마케팅전략':'marketing_strategy', '일상정보':'daily_information', '시즌정보':'season_information', '분류':'type', '제목':'title', '본문':'content', '납품차수':'degree'}, inplace=True)

In [11]:
df.head()

,no,advertisement_type,marketing_strategy,daily_information,season_information,type,title,content,degree
0,1,NaN,NaN,NaN,NaN,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰,"마지막 2일! [계절밥상 디너/주말 1만원, 런치 5천원 할인 쿠폰] 9월30일까지...",NaN
1,1,할인/쿠폰/혜택,"매력적인숫자(시간,돈)",NaN,NaN,ST,★최대 1만원★ 계절밥상 할인쿠폰,"이.틀.만! VIP 고객 디너&주말 1만원, 런치 5천원 할인 쿠폰 놓치지 마세요!",1차
2,1,할인/쿠폰/혜택,핵심정보만 전달,NaN,NaN,SF,ONLY VIP! 할인쿠폰♬,소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상] 디너/주말 1만원+런치 5천...,1차
3,1,할인/쿠폰/혜택,호기심유발(질문),NaN,NaN,NT,이 혜택💰 놓치지 않을 거예요,"[계절밥상] 디너/주말 1O,OOO원, 런치 5,OOO원 할인\\9월 30일까지🚨",1차
4,1,할인/쿠폰/혜택,호기심유발(이모지),NaN,NaN,NF,VIP님들만을 위한 쿠폰 도착💌,계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/주말 할인 쿠폰(~9/30) 사용하...,1차

원문 제거 & 1,000건

In [12]:
df_nt = df[df.type.str.contains("NT")][:1000]
df_nf = df[df.type.str.contains("NF")][:1000]

In [13]:
df = pd.concat([df_nt, df_nf])

In [14]:
print(df.type.value_counts())
print(df.shape)

NT    1000
NF    1000
Name: type, dtype: int64
(2000, 9)

# Preprocessing

In [15]:
from pshmodule.processing import processing as p

In [16]:
nlp = p.Nlp()

In [17]:
df_temp = df.copy()

In [18]:
# \\\\ → \\
df_temp['title_processing'] = df_temp.title.swifter.apply(lambda x: x.replace('\\\\', '\\'))
df_temp['content_processing'] = df_temp.content.swifter.apply(lambda x: x.replace('\\\\', '\\'))

# \n\n -> \\\\
df_temp['title_processing'] = df_temp.title_processing.replace('\n\n', '\\\\').replace('\n', '\\')
df_temp['content_processing'] = df_temp.content_processing.replace('\n\n', '\\\\').replace('\n', '\\')

Pandas Apply:   0%|          | 0/2000 [00:00<?, ?it/s]

In [19]:
df_temp['input'] = df_temp.title_processing + '\\\\' + df_temp.content_processing
df_temp['origin'] = df_temp.title + '\\\\' + df_temp.content

In [20]:
df_temp.head()

,no,advertisement_type,marketing_strategy,daily_information,season_information,type,title,content,degree,title_processing,content_processing,input,origin
3,1,할인/쿠폰/혜택,호기심유발(질문),NaN,NaN,NT,이 혜택💰 놓치지 않을 거예요,"[계절밥상] 디너/주말 1O,OOO원, 런치 5,OOO원 할인\\9월 30일까지🚨",1차,이 혜택💰 놓치지 않을 거예요,"[계절밥상] 디너/주말 1O,OOO원, 런치 5,OOO원 할인\9월 30일까지🚨","이 혜택💰 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,OOO원, 런치 5,O...","이 혜택💰 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,OOO원, 런치 5,O..."
8,2,기타 이벤트,"매력적인숫자(시간,돈)",NaN,NaN,NT,무조건 당첨인데 참여 외않해?👀,5OOP만 있으면 무조건 당첨되는 갓-이벤트✨\\2OO만원 상당 여행권에 빕스 쿠폰...,1차,무조건 당첨인데 참여 외않해?👀,5OOP만 있으면 무조건 당첨되는 갓-이벤트✨\2OO만원 상당 여행권에 빕스 쿠폰까...,무조건 당첨인데 참여 외않해?👀\\5OOP만 있으면 무조건 당첨되는 갓-이벤트✨\2...,무조건 당첨인데 참여 외않해?👀\\5OOP만 있으면 무조건 당첨되는 갓-이벤트✨\\...
13,3,할인/쿠폰/혜택,호기심유발(질문),NaN,NaN,NT,아직 손도 안 댄 쿠폰이 있어요!,미사용 쿠폰 만료까지 D-7🚨 쿠폰함으로 확인하러 가기👉,1차,아직 손도 안 댄 쿠폰이 있어요!,미사용 쿠폰 만료까지 D-7🚨 쿠폰함으로 확인하러 가기👉,아직 손도 안 댄 쿠폰이 있어요!\\미사용 쿠폰 만료까지 D-7🚨 쿠폰함으로 확인하...,아직 손도 안 댄 쿠폰이 있어요!\\미사용 쿠폰 만료까지 D-7🚨 쿠폰함으로 확인하...
18,4,할인/쿠폰/혜택,호기심유발(질문),NaN,주말,NT,주말엔 사라질 그 할인쿠폰!,[OOOO 1만원 할인쿠폰] 의 유효기간은 이번 주 일요일까지🚨\\쫀득한 통돼지구이...,1차,주말엔 사라질 그 할인쿠폰!,[OOOO 1만원 할인쿠폰] 의 유효기간은 이번 주 일요일까지🚨\쫀득한 통돼지구이를...,주말엔 사라질 그 할인쿠폰!\\[OOOO 1만원 할인쿠폰] 의 유효기간은 이번 주 ...,주말엔 사라질 그 할인쿠폰!\\[OOOO 1만원 할인쿠폰] 의 유효기간은 이번 주 ...
23,9,할인/쿠폰/혜택,"매력적인숫자(시간,돈)",NaN,휴가(바캉스),NT,OO 바캉스 위크 특가⚡누리세오!,"아참, 득템프 1회 더 찍으면 5,OOO원 할인 쿠폰도 드린답니다",1차,OO 바캉스 위크 특가⚡누리세오!,"아참, 득템프 1회 더 찍으면 5,OOO원 할인 쿠폰도 드린답니다","OO 바캉스 위크 특가⚡누리세오!\\아참, 득템프 1회 더 찍으면 5,OOO원 할인...","OO 바캉스 위크 특가⚡누리세오!\\아참, 득템프 1회 더 찍으면 5,OOO원 할인..."

In [21]:
df_temp = df_temp[['type', 'input']]

In [22]:
df_temp.head()

   type                                              input
3    NT  이 혜택💰 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,OOO원, 런치 5,O...
8    NT  무조건 당첨인데 참여 외않해?👀\\5OOP만 있으면 무조건 당첨되는 갓-이벤트✨\2...
13   NT  아직 손도 안 댄 쿠폰이 있어요!\\미사용 쿠폰 만료까지 D-7🚨 쿠폰함으로 확인하...
18   NT  주말엔 사라질 그 할인쿠폰!\\[OOOO 1만원 할인쿠폰] 의 유효기간은 이번 주 ...
23   NT  OO 바캉스 위크 특가⚡누리세오!\\아참, 득템프 1회 더 찍으면 5,OOO원 할인...

In [23]:
df_temp.shape

(2000, 2)

# Save

In [24]:
fm.save(cfg.for_gpt4, df_temp)

Saved 2000 records

# ChatGPT Test

GPT4

In [ ]:
import openai

In [ ]:
# 발급받은 API 키 설정
OPENAI_API_KEY = "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"

# openai API 키 인증
openai.api_key = OPENAI_API_KEY
model = "gpt-4"

In [ ]:
def generate_response(messages):
  response = openai.ChatCompletion.create(
      model=model,
      messages=messages
  )
  return response['choices'][0]['message']['content']

##### MBTI 추출

In [ ]:
predict = []

for i in tqdm(df_temp.iterrows()):
  messages = [
      {"role": "system", "content": f"""너는 판매 촉진을 위한 마케팅 문구를 만드는 카피라이터야.\n
                                        아래 예시처럼 ''안에 있는 원문에서 ST, NT, SF, NF MBTI 성향 별로 각각에 해당하는 마케팅 문구를 추출할거야\n
                                        '이번 봄 나들이는 빕스로❓\\\\제철 과일 딸기 가득 [딸기홀릭] 시즌♥ 시크릿박스 쿠폰 쓰고 딸기 디저트 저.렴.하.게 즐기자'
                                        ST 성향 문구 : 시크릿박스 쿠폰 쓰고 딸기 디저트 저.렴.하.게 즐기자, NT 성향 문구 : 없음, SF 성향 문구 : 없음, NF 성향 문구 : 없음\n
                                        '갈 땐 가더라도...(진지)\\\\[뮤지엄오브컬러展] 3O% 할인 쿠폰💌 쓰는 것 정돈 괜찮잖아? 은하수를 닮은 다채로운 색감의 향연✨ 거 쿠폰 쓰기 딱 좋은 전시네💕
                                        ST 성향 문구 : 없음, NT 성향 문구 : 갈 땐 가더라도...(진지), [뮤지엄오브컬러展] 3O% 할인 쿠폰💌 쓰는 것 정돈 괜찮잖아?, 은하수를 닮은 다채로운 색감의 향연✨, 거 쿠폰 쓰기 딱 좋은 전시네💕, SF 성향 문구 : 없음, NF 성향 문구 : 없음\n
                                        '한겨울엔 따뜻한 박물관으로 GO!\\\\고객님께만 드리는 단독 할인! 국립중앙박물관 호랑이 전시 1+1! 마감 D-1✔️
                                        ST 성향 문구 : 없음, NT 성향 문구 : 없음, SF 성향 문구 : 고객님께만 드리는 단독 할인, NF 성향 문구 : 없음\n
                                        '옛날옛날에~호랑이가 살았어요🦁\\\\아직도 안 가본 사람?(어흥)😨 국립중앙박물관에서 호랑이를 만나보세요⭐ 지금 1+1 할인중!
                                        ST 성향 문구 : 없음, NT 성향 문구 : 없음, SF 성향 문구 : 없음, NF 성향 문구 : 옛날옛날에~호랑이가 살았어요🦁, 아직도 안 가본 사람?(어흥)😨\n
                                        '짝짝짝! 친구 맺으면 1,000P~\\\\정답만 맞히면 포인트 주는 이벤트! 퀴즈 맞히고 1,000P 바로 받아가기'
                                        ST 성향 문구 : 정답만 맞히면 포인트 주는, NT 성향 문구 : 없음, SF 성향 문구 : 없음, NF 성향 문구 : 없음\n
                                        '🐯: 어흥!(전시 할인 중!)\\\\⌛내/일/까/지/만 [국립중앙박물관 호랑이展] 1+1 할인⚡\\할인도 2배 호랑이 기운도 2배로 받을 기회!✌️ 절대 놓치지 마세흥!
                                        ST 성향 문구 : 없음, NT 성향 문구 : 🐯: 어흥!(전시 할인 중!), ⌛내/일/까/지/만, SF 성향 문구 : 없음, NF 성향 문구 : 없음\n
                                        '투썸 빙수 먹으면 아메리카노가 공짜!\\\\올 여름 더위 물리치는 투썸 빙수가 왔다!\\빙수 포함 5개 득템프 찍으면 아메리카노가 O원!
                                        ST 성향 문구 : 없음, NT 성향 문구 : 없음, SF 성향 문구 : 올 여름 더위 물리치는 투썸 빙수가 왔다!, NF 성향 문구 : 없음\n
                                        '힙스터들의 성지, 성수동 갈 사람?\\\\🔥화제의 팝업 전시, 뮤지엄오브컬러가 고객님을 기다려욧!\\힙쟁이라면 안 간 사람 없다던데👁️...단독 3O% 할인 중
                                        ST 성향 문구 : 없음, NT 성향 문구 : 없음, SF 성향 문구 : 없음, NF 성향 문구 : 힙스터들의 성지, 성수동 갈 사람?, 🔥화제의 팝업 전시, 뮤지엄오브컬러가 고객님을 기다려욧!, 힙쟁이라면 안 간 사람 없다던데👁️\n
                                        ST, SF, NT, NF의 특징을 알려줄게\n
                                        ST 유형 : 현실 강조 워딩 사용 (예 : 지금, 여기, 바로, 당장), 첫 줄에 혜택 정보(마감 정보, 할인 수치 등) 강조, 작은 노력으로 큰 이득 강조 (예 : 클릭만 하면 받을 수 있다), 제품의 효과, 효능, 전문성, 신뢰성 강조
                                        SF 유형 : 명료하고 직관적인 워딩 사용, 고객을 위해주는, 특별하게 생각하는 듯한 메시지 (예 : 특별히 고객님께만 드려요, 우리 고객님 드시라고, 사랑하는 고객님 등)
                                        NT 유형 : 비유적, 추상적 수사 방식 사용, 첫 줄에 혜택 정보(마감 정보, 할인 수치 등) 강조, 노래 가사, 영화 대사, 광고 문구, 밈, 이모지 활용 (예 : 외식하기 딱 좋은 날이네, 숨 참고 할인 다이브 등), 제품의 효과, 효능, 전문성, 신뢰성 강조
                                        NF 유형 : 비유적, 추상적 수사 방식 사용, 노래 가사, 영화 대사, 광고 문구, 밈, 이모지 활용, 고객을 위해주는, 특별하게 생각하는 듯한 메시지"""},
      {"role": "user", "content": f"""{i[1]['input']}\n
                                      위 문장에서 아래 정보를 뽑아줘.
                                      ST 성향 문구 : ,\n
                                      NT 성향 문구 : ,\n
                                      SF 성향 문구 : ,\n
                                      NF 성향 문구 : """}
  ]
  result = generate_response(messages)
  # print(f"원문 : {i[1]['input']}")
  # print(f"답변 : {result}")
  # print("-"*100)
  predict.append(result)

10it [04:31, 27.14s/it]

In [ ]:
df_temp['mbti'] = predict

In [ ]:
df_temp['mbti_temp'] = df_temp.mbti.swifter.apply(lambda x: x.replace('ST 성향 문구 : ', '').replace('NT 성향 문구 : ', '').replace('SF 성향 문구 : ', '').replace('NF 성향 문구 : ', ''))

Pandas Apply:   0%|          | 0/10 [00:00<?, ?it/s]

In [ ]:
df_temp.head()

,type,input,origin,mbti,mbti_temp
0,SF,나이키 시즌베스트 최고73%▼\\오늘 끝! 초.특.가 즐길 라스트 찬스✔️\고객님을...,나이키 시즌베스트 최고73%▼\\오늘 끝! 초.특.가 즐길 라스트 찬스✔️\\고객님...,ST 성향 문구 : 오늘 끝! 초.특.가 즐길 라스트 찬스✔️\n\nNT 성향 문구...,오늘 끝! 초.특.가 즐길 라스트 찬스✔️\n\n없음\n\n고객님을 위한 SNS대란...
1,SF,원래 성실한 사람 못 이기는 법!\\날마다 오실 분 손❕\올 때마다 꿀이득♥ APP...,원래 성실한 사람 못 이기는 법!\\날마다 오실 분 손❕\\올 때마다 꿀이득♥ AP...,"ST 성향 문구 : 날마다 오실 분 손❕, 올 때마다 꿀이득♥, APP에서 출첵할 ...","날마다 오실 분 손❕, 올 때마다 꿀이득♥, APP에서 출첵할 때마다 최대 1OO포..."
2,NT,훠이훠이~ 세균아 물러가라🧫\\초/특/가 73% 할인 중인⚡ [수저살균기]로 세균 ...,훠이훠이~ 세균아 물러가라🧫\\초/특/가 73% 할인 중인⚡ [수저살균기]로 세균 ...,"ST 성향 문구 : 초/특/가 73% 할인 중인⚡, [수저살균기]로 세균 타파하고 ...","초/특/가 73% 할인 중인⚡, [수저살균기]로 세균 타파하고 2,OOOP 추가 적..."
3,NF,통닭! 돌립니다 돌리는 겁니다🍗\\고객님을 위해 SUBWAY가 준비한 2만 포인트⭐...,통닭! 돌립니다 돌리는 겁니다🍗\\고객님을 위해 SUBWAY가 준비한 2만 포인트⭐...,ST 성향 문구 : 고객님을 위해 SUBWAY가 준비한 2만 포인트⭐ 드리고 싶어서...,고객님을 위해 SUBWAY가 준비한 2만 포인트⭐ 드리고 싶어서 만든 이벤트👉\n\...
4,ST,1번만 더 찍으면 777포인트가 쏘옥\\7주년 행운 이벤트♥ 득템프 4번 찍은 고객...,1번만 더 찍으면 777포인트가 쏘옥\\7주년 행운 이벤트♥ 득템프 4번 찍은 고객...,ST 성향 문구 : 1번만 더 찍으면 777포인트가 쏘옥\n\nNT 성향 문구 : ...,1번만 더 찍으면 777포인트가 쏘옥\n\n없음\n\n7주년 행운 이벤트♥ 득템프 ...

In [ ]:
df_split_mbti = df_temp.mbti_temp.str.split(',\n\n', expand=True)

In [ ]:
df_split_mbti_true = df_split_mbti[df_split_mbti[0].str.contains('\n\n')]
df_split_mbti_true = df_split_mbti_true[0].str.split('\n\n', expand=True)

In [ ]:
df_split_mbti_false = df_split_mbti[~df_split_mbti[0].str.contains('\n\n')]

In [ ]:
print(df_split_mbti_false.shape)
print(df_split_mbti_true.shape)

(1, 3)
(9, 4)

In [ ]:
df_split_mbti_temp = pd.concat([df_split_mbti_false, df_split_mbti_true])

In [ ]:
df_split_mbti_temp.rename(columns={0:'ST', 1:'NT',	2:'SF', 3:'NF'}, inplace=True)

In [ ]:
df_temp1 = pd.concat([df_split_mbti_temp, df_temp], axis=1)

In [ ]:
df_temp1 = df_temp1.sort_index(ascending=True)

In [ ]:
df_temp1 = df_temp1[['ST', 'NT', 'SF', 'NF', 'type', 'input', 'origin']]

In [ ]:
df_temp1.head()

,ST,NT,SF,NF,type,input,origin
0,오늘 끝! 초.특.가 즐길 라스트 찬스✔️,없음,고객님을 위한 SNS대란템 특전,인싸되기▶,SF,나이키 시즌베스트 최고73%▼\\오늘 끝! 초.특.가 즐길 라스트 찬스✔️\고객님을...,나이키 시즌베스트 최고73%▼\\오늘 끝! 초.특.가 즐길 라스트 찬스✔️\\고객님...
1,"날마다 오실 분 손❕, 올 때마다 꿀이득♥, APP에서 출첵할 때마다 최대 1OO포...",없음,None,None,SF,원래 성실한 사람 못 이기는 법!\\날마다 오실 분 손❕\올 때마다 꿀이득♥ APP...,원래 성실한 사람 못 이기는 법!\\날마다 오실 분 손❕\\올 때마다 꿀이득♥ AP...
2,"초/특/가 73% 할인 중인⚡, [수저살균기]로 세균 타파하고 2,OOOP 추가 적...",없음,없음,"훠이훠이~ 세균아 물러가라🧫, 이런 세일 언제 또 올지 모릅니다~?👀",NT,훠이훠이~ 세균아 물러가라🧫\\초/특/가 73% 할인 중인⚡ [수저살균기]로 세균 ...,훠이훠이~ 세균아 물러가라🧫\\초/특/가 73% 할인 중인⚡ [수저살균기]로 세균 ...
3,고객님을 위해 SUBWAY가 준비한 2만 포인트⭐ 드리고 싶어서 만든 이벤트👉,없음,고객님을 위해 SUBWAY가 준비한 2만 포인트⭐ 드리고 싶어서 만든 이벤트👉,통닭! 돌립니다 돌리는 겁니다🍗,NF,통닭! 돌립니다 돌리는 겁니다🍗\\고객님을 위해 SUBWAY가 준비한 2만 포인트⭐...,통닭! 돌립니다 돌리는 겁니다🍗\\고객님을 위해 SUBWAY가 준비한 2만 포인트⭐...
4,1번만 더 찍으면 777포인트가 쏘옥,없음,"7주년 행운 이벤트♥ 득템프 4번 찍은 고객님, 1번만 추가하면 포인트 혜택 와르르♬",없음,ST,1번만 더 찍으면 777포인트가 쏘옥\\7주년 행운 이벤트♥ 득템프 4번 찍은 고객...,1번만 더 찍으면 777포인트가 쏘옥\\7주년 행운 이벤트♥ 득템프 4번 찍은 고객...

##### 마케팅 정보 추출

In [ ]:
predict = []

for i in tqdm(df_temp1.iterrows()):
  messages = [
      {"role": "system", "content": f"""너는 판매 촉진을 위한 마케팅 문구를 만드는 카피라이터야.\n
                                        아래 예시처럼 ''안에 있는 원문에서 마케팅 주체, 타겟, 혜택 지급 조건, 혜택, 할인수치, 프로모션품목, 프로모션장소, 이벤트기간, 요일정보, 시즌정보, 소구점을 추출할거야\n
                                        '이번 봄 나들이는 빕스로❓\\\\제철 과일 딸기 가득 [딸기홀릭] 시즌♥ 시크릿박스 쿠폰 쓰고 딸기 디저트 저.렴.하.게 즐기자'
                                        마케팅 주체 : 빕스, 타겟 : 없음, 혜택 지급 조건 : 없음, 혜택 : 시크릿박스 쿠폰, 할인 수치 : 없음, 프로모션 품목 : [딸기 홀릭] 시즌, 프로모션 장소 : 없음, 이벤트 기간 : 없음, 요일 정보 : 없음, 시즌 정보 : 봄, 소구점 : 봄 나들이, 제철 과일\n
                                        '갈 땐 가더라도...(진지)\\\\[뮤지엄오브컬러展] 3O% 할인 쿠폰💌 쓰는 것 정돈 괜찮잖아? 은하수를 닮은 다채로운 색감의 향연✨ 거 쿠폰 쓰기 딱 좋은 전시네💕'
                                        마케팅 주체 : 없음, 타겟 : 없음, 혜택 지급 조건 : 할인 쿠폰 쓰기, 혜택 : 30% 할인 쿠폰, 할인 수치 : 0.3, 프로모션 품목 : 뮤지엄오브컬러展, 프로모션 장소 : 없음, 이벤트 기간 : 없음, 요일 정보 : 없음, 시즌 정보 : 없음, 소구점 : 없음\n
                                        '한겨울엔 따뜻한 박물관으로 GO!\\\\고객님께만 드리는 단독 할인! 국립중앙박물관 호랑이 전시 1+1! 마감 D-1✔️'
                                        마케팅 주체 : 국립중앙박물관, 타겟 : 고객님, 혜택 지급 조건 : 없음, 혜택 : 단독 할인, 1+1, 할인 수치 : 1+1, 프로모션 품목 : 호랑이 전시, 프로모션 장소 : 없음, 이벤트 기간 : D-1, 요일 정보 : 없음, 시즌 정보 : 겨울맞이, 소구점 : 한겨울엔 따뜻한 박물관으로\n
                                        '옛날옛날에~호랑이가 살았어요🦁\\\\아직도 안 가본 사람?(어흥)😨 국립중앙박물관에서 호랑이를 만나보세요⭐ 지금 1+1 할인중!
                                        마케팅 주체 : 국립중앙박물관, 타겟 : 없음, 혜택 지급 조건 : 없음, 혜택 : 1+1 할인, 할인 수치 : 1+1, 프로모션 품목 : 없음, 프로모션 장소 : 없음, 이벤트 기간 : 없음, 요일 정보 : 없음, 시즌 정보 : 없음, 소구점 : 없음\n
                                        '짝짝짝! 친구 맺으면 1,000P~\\\\정답만 맞히면 포인트 주는 이벤트! 퀴즈 맞히고 1,000P 바로 받아가기'
                                        마케팅 주체 : 없음, 타겟 : 없음, 혜택 지급 조건 : 친구맺기, 퀴즈 맞히기, 혜택 : 1000P, 할인 수치 : 없음, 프로모션 품목 : 없음, 프로모션 장소 : 없음, 이벤트 기간 : 없음, 요일 정보 : 없음, 시즌 정보 : 없음, 소구점 : 없음\n
                                        '🐯: 어흥!(전시 할인 중!)\\\\⌛내/일/까/지/만 [국립중앙박물관 호랑이展] 1+1 할인⚡\\할인도 2배 호랑이 기운도 2배로 받을 기회!✌️ 절대 놓치지 마세흥!'
                                        마케팅 주체 : 국립중앙박물관, 타겟 : 없음, 혜택 지급 조건 : 없음, 혜택 : 1+1 할인, 할인 수치 : 1+1, 프로모션 품목 : 호랑이展, 프로모션 장소 : 없음, 이벤트 기간 : 내일까지, 요일 정보 : 없음, 시즌 정보 : 없음, 소구점 : 없음\n
                                        '투썸 빙수 먹으면 아메리카노가 공짜!\\\\올 여름 더위 물리치는 투썸 빙수가 왔다!\\빙수 포함 5개 득템프 찍으면 아메리카노가 O원!'
                                        마케팅 주체 : 투썸, 타겟 : 없음, 혜택 지급 조건 : 빙수 포함 5개 득템프 찍기, 혜택 : 1+1 할인, 할인 수치 : 없음, 프로모션 품목 : 빙수, 프로모션 장소 : 없음, 이벤트 기간 : 없음, 요일 정보 : 없음, 시즌 정보 : 여름맞이, 소구점 : 더위 물리치는 투썸 빙수\n
                                        '힙스터들의 성지, 성수동 갈 사람?\\\\🔥화제의 팝업 전시, 뮤지엄오브컬러가 고객님을 기다려욧!\\힙쟁이라면 안 간 사람 없다던데👁️...단독 3O% 할인 중'
                                        마케팅 주체 : 없음, 타겟 : 고객님, 혜택 지급 조건 : 없음, 혜택 : 30% 할인, 할인 수치 : 0.3, 프로모션 품목 : 뮤지엄오브컬러, 프로모션 장소 : 성수동, 이벤트 기간 : 없음, 요일 정보 : 없음, 시즌 정보 : 없음, 소구점 : 없음"""},
      {"role": "user", "content": f"""{i[1]['input']}\n
                                      위 문장에서 아래 정보를 뽑아줘.
                                      마케팅 주체 : ,\n
                                      타겟 : ,\n
                                      혜택 지급 조건 : ,\n
                                      혜택 : ,\n
                                      할인 수치 : ,\n
                                      프로모션 품목 : ,\n
                                      프로모션 장소 : ,\n
                                      이벤트 기간 : ,\n
                                      요일 정보 : ,\n
                                      시즌 정보 : ,\n
                                      소구점 : """}
  ]
  result = generate_response(messages)
  print(f"원문 : {i[1]['input']}")
  print(f"답변 : {result}")
  print("-"*100)
  predict.append(result)

후처리

In [ ]:
df_temp1['marketing'] = predict

In [ ]:
df_temp1['marketing_temp'] = df_temp1.marketing.swifter.apply(lambda x: x.replace('마케팅 주체 : ', '').replace('타겟 : ', '').replace('혜택 지급 조건 : ', '').replace('혜택 : ', '').replace('할인 수치 : ', '').replace('프로모션 품목 : ', '').replace('프로모션 장소 : ', '').replace('이벤트 기간 : ', '').replace('요일 정보 : ', '').replace('시즌 정보 : ', '').replace('소구점 : ', ''))

Pandas Apply:   0%|          | 0/10 [00:00<?, ?it/s]

In [ ]:
df_temp1.head()

,ST,NT,SF,NF,type,input,origin,marketing,marketing_temp
0,"증권계좌 만들면 1만P 즉/시/지/급, 높은 수익률 보장되는 KB증권 비대면 계좌 ...",없음,특별 우대수익률,없음,ST,증권계좌 만들면 1만P 즉/시/지/급\\높은 수익률 보장되는 KB증권 비대면 계좌 ...,증권계좌 만들면 1만P 즉/시/지/급\\높은 수익률 보장되는 KB증권 비대면 계좌 ...,"마케팅 주체 : KB증권,\n\n타겟 : 없음,\n\n혜택 지급 조건 : 비대면 계...","KB증권,\n\n없음,\n\n비대면 계좌 개설,\n\n1만P, 특별 우대수익률 세전..."
1,"아이패드 에어+애플워치+마샬 스피커+다이슨 에어랩🎁를 준다구요!, 딱 1O초만⏰ 투...",없음,None,None,NT,선물 받으러 팔로팔로미!🙋\\지금 [올리브영] 인스타 팔로우하면 아이패드 에어+애플...,선물 받으러 팔로팔로미!🙋\\지금 [올리브영] 인스타 팔로우하면 아이패드 에어+애플...,"마케팅 주체 : 올리브영,\n\n타겟 : 없음,\n\n혜택 지급 조건 : 인스타 팔...","올리브영,\n\n없음,\n\n인스타 팔로우,\n\n아이패드 에어, 애플워치, 마샬 ..."
2,오.늘.부.터 원더락 5일 유지하면✋ 최대 깊카 1만원권 드림💌,응모는 필수 유지도 필수🎵,없음,응모하러 가볼까요?☞,NT,응모는 필수 유지도 필수🎵\\오.늘.부.터 원더락 5일 유지하면✋ 최대 깊카 1만원...,응모는 필수 유지도 필수🎵\\오.늘.부.터 원더락 5일 유지하면✋ 최대 깊카 1만원...,"마케팅 주체 : 없음,\n\n타겟 : 없음,\n\n혜택 지급 조건 : 원더락 5일 ...","없음,\n\n없음,\n\n원더락 5일 유지,\n\n깊카 1만원권,\n\n없음,\n\..."
3,[니키 드 생팔] 1+1 할인권 증정!,"서울에 사격 회화의 거장 도착♬, 예술의 전당으로 컴컴♥",[TAG1]님 쿠폰 확인하고,없음,ST,서울에 사격 회화의 거장 도착♬\\[니키 드 생팔] 1+1 할인권 증정!\[TAG1...,서울에 사격 회화의 거장 도착♬\\[니키 드 생팔] 1+1 할인권 증정!\\[TAG...,"마케팅 주체 : 예술의 전당,\n\n타겟 : [TAG1]님,\n\n혜택 지급 조건 ...","예술의 전당,\n\n[TAG1]님,\n\n쿠폰 확인,\n\n1+1 할인권 증정,\n..."
4,제일제면소 비빔소면 1개를 무료로 드세요(~6/30),"속은 두둑이🍜손은 가볍게🖐🏻, 비빔소면 한 젓가락에 행복은 두 젓가락🥢",없음,없음,NF,속은 두둑이🍜손은 가볍게🖐🏻\\비빔소면 한 젓가락에 행복은 두 젓가락🥢\제일제면소 ...,속은 두둑이🍜손은 가볍게🖐🏻\\비빔소면 한 젓가락에 행복은 두 젓가락🥢\\제일제면소...,"마케팅 주체 : 제일제면소,\n\n타겟 : 없음,\n\n혜택 지급 조건 : 없음,\...","제일제면소,\n\n없음,\n\n없음,\n\n비빔소면 1개 무료,\n\n없음,\n\n..."

In [ ]:
df_split_marketing = df_temp1.marketing_temp.str.split(',\n\n', expand=True)

In [ ]:
df_split_marketing_true = df_split_marketing[df_split_marketing[0].str.contains('\n\n')]
df_split_marketing_true = df_split_marketing_true[0].str.split('\n\n', expand=True)

In [ ]:
df_split_marketing_false = df_split_marketing[~df_split_marketing[0].str.contains('\n\n')]

In [ ]:
print(df_split_marketing_false.shape)
print(df_split_marketing_true.shape)

(10, 11)
(0, 0)

In [ ]:
df_split_marketing_temp = pd.concat([df_split_marketing_false, df_split_marketing_true])

In [ ]:
# 마케팅 주체: marketing_entity, 타겟: marketing_target, 혜택 지급 조건: benefit_conditions, 혜택: benefits, 할인 수치: discount_figure, 프로모션 품목: promotional_items, 프로모션 장소: promotional_place, 이벤트 기간: event_period, 요일 정보: dow_information, 시즌 정보: season_information, 소구점: solicitation_point
df_split_marketing_temp.rename(columns={0:'marketing_entity', 1:'marketing_target',	2:'benefit_conditions', 3:'benefits', 4:'discount_figure', 5:'promotional_items', 6:'promotional_place', 7:'event_period', 8:'dow_information', 9:'season_information', 10:'solicitation_point'}, inplace=True)

In [ ]:
df_split_marketing_temp.head(10)

,marketing_entity,marketing_target,benefit_conditions,benefits,discount_figure,promotional_items,promotional_place,event_period,dow_information,season_information,solicitation_point
0,KB증권,없음,비대면 계좌 개설,"1만P, 특별 우대수익률 세전 연 5%",없음,증권계좌,없음,없음,없음,없음,높은 수익률 보장
1,올리브영,없음,인스타 팔로우,"아이패드 에어, 애플워치, 마샬 스피커, 다이슨 에어랩",없음,없음,없음,없음,없음,없음,없음
2,없음,없음,원더락 5일 유지,깊카 1만원권,없음,없음,없음,5일,오늘부터,없음,없음
3,예술의 전당,[TAG1]님,쿠폰 확인,1+1 할인권 증정,1+1,니키 드 생팔 전시,예술의 전당,없음,없음,없음,서울에 사격 회화의 거장 도착
4,제일제면소,없음,없음,비빔소면 1개 무료,없음,비빔소면,없음,~6/30,없음,없음,"속은 두둑이, 손은 가볍게, 행복은 두 젓가락"
5,없음,없음,구매,"48% 할인, 1,500P 추가 적립",0.48,여름용 얇은 마스크,없음,없음,없음,여름,무더위에도 끄떡없는 여름용 얇은 마스크
6,올영,없음,없음,특가,없음,BEST 인기템들,없음,단 하루,없음,없음,마지막 기회
7,투썸,없음,없음,할인쿠폰,없음,투썸 X 모나미 콜라보 키트,없음,없음,없음,없음,"조기 소진 예감, 내일은 재고 없음"
8,올리브영,선물 구매자,없음,기프트카드,없음,올리브영 기프트카드,없음,없음,없음,없음,선물 살 때 고민 없애기
9,계절밥상,고객님,주말에 사용하기,1만 원 할인 쿠폰,10000 원,없음,없음,만료 전,주말,없음,없음

In [ ]:
df_result = pd.concat([df_split_marketing_temp, df_temp1], axis=1)

In [ ]:
df_result = df_result.sort_index(ascending=True)

In [ ]:
df_result.fillna('없음', inplace=True)

In [ ]:
df_result = df_result[['type', 'ST', 'NT', 'SF', 'NF', 'input', 'marketing_entity', 'marketing_target', 'benefit_conditions', 'benefits', 'discount_figure', 'promotional_items', 'promotional_place', 'event_period', 'dow_information', 'season_information', 'solicitation_point']]

In [ ]:
df_result.head()

,구분,ST 성향 문구,NT 성향 문구,SF 성향 문구,NF 성향 문구,원문,마케팅 주체,타겟,혜택 지급 조건,혜택,할인 수치,프로모션 품목,프로모션 장소,이벤트 기간,요일 정보,시즌 정보,소구점
0,ST,"증권계좌 만들면 1만P 즉/시/지/급, 높은 수익률 보장되는 KB증권 비대면 계좌 ...",없음,특별 우대수익률,없음,증권계좌 만들면 1만P 즉/시/지/급\\높은 수익률 보장되는 KB증권 비대면 계좌 ...,KB증권,없음,비대면 계좌 개설,"1만P, 특별 우대수익률 세전 연 5%",없음,증권계좌,없음,없음,없음,없음,높은 수익률 보장
1,NT,"아이패드 에어+애플워치+마샬 스피커+다이슨 에어랩🎁를 준다구요!, 딱 1O초만⏰ 투...",없음,없음,없음,선물 받으러 팔로팔로미!🙋\\지금 [올리브영] 인스타 팔로우하면 아이패드 에어+애플...,올리브영,없음,인스타 팔로우,"아이패드 에어, 애플워치, 마샬 스피커, 다이슨 에어랩",없음,없음,없음,없음,없음,없음,없음
2,NT,오.늘.부.터 원더락 5일 유지하면✋ 최대 깊카 1만원권 드림💌,응모는 필수 유지도 필수🎵,없음,응모하러 가볼까요?☞,응모는 필수 유지도 필수🎵\\오.늘.부.터 원더락 5일 유지하면✋ 최대 깊카 1만원...,없음,없음,원더락 5일 유지,깊카 1만원권,없음,없음,없음,5일,오늘부터,없음,없음
3,ST,[니키 드 생팔] 1+1 할인권 증정!,"서울에 사격 회화의 거장 도착♬, 예술의 전당으로 컴컴♥",[TAG1]님 쿠폰 확인하고,없음,서울에 사격 회화의 거장 도착♬\\[니키 드 생팔] 1+1 할인권 증정!\[TAG1...,예술의 전당,[TAG1]님,쿠폰 확인,1+1 할인권 증정,1+1,니키 드 생팔 전시,예술의 전당,없음,없음,없음,서울에 사격 회화의 거장 도착
4,NF,제일제면소 비빔소면 1개를 무료로 드세요(~6/30),"속은 두둑이🍜손은 가볍게🖐🏻, 비빔소면 한 젓가락에 행복은 두 젓가락🥢",없음,없음,속은 두둑이🍜손은 가볍게🖐🏻\\비빔소면 한 젓가락에 행복은 두 젓가락🥢\제일제면소 ...,제일제면소,없음,없음,비빔소면 1개 무료,없음,비빔소면,없음,~6/30,없음,없음,"속은 두둑이, 손은 가볍게, 행복은 두 젓가락"

##### For Report

In [ ]:
df_result.rename(columns={'type':'구분', 'ST':'ST 성향 문구', 'NT':'NT 성향 문구', 'SF':'SF 성향 문구', 'NF':'NF 성향 문구', 'input':'원문', 'marketing_entity':'마케팅 주체', 'marketing_target':'타겟', 'benefit_conditions':'혜택 지급 조건', 'benefits':'혜택', 'discount_figure':'할인 수치', 'promotional_items':'프로모션 품목', 'promotional_place': '프로모션 장소', 'event_period':'이벤트 기간', 'dow_information':'요일 정보', 'season_information':'시즌 정보', 'solicitation_point':'소구점'}, inplace=True)

In [ ]:
df_result.head()

,구분,ST 성향 문구,NT 성향 문구,SF 성향 문구,NF 성향 문구,원문,마케팅 주체,타겟,혜택 지급 조건,혜택,할인 수치,프로모션 품목,프로모션 장소,이벤트 기간,요일 정보,시즌 정보,소구점
0,ST,"증권계좌 만들면 1만P 즉/시/지/급, 높은 수익률 보장되는 KB증권 비대면 계좌 ...",없음,특별 우대수익률,없음,증권계좌 만들면 1만P 즉/시/지/급\\높은 수익률 보장되는 KB증권 비대면 계좌 ...,KB증권,없음,비대면 계좌 개설,"1만P, 특별 우대수익률 세전 연 5%",없음,증권계좌,없음,없음,없음,없음,높은 수익률 보장
1,NT,"아이패드 에어+애플워치+마샬 스피커+다이슨 에어랩🎁를 준다구요!, 딱 1O초만⏰ 투...",없음,없음,없음,선물 받으러 팔로팔로미!🙋\\지금 [올리브영] 인스타 팔로우하면 아이패드 에어+애플...,올리브영,없음,인스타 팔로우,"아이패드 에어, 애플워치, 마샬 스피커, 다이슨 에어랩",없음,없음,없음,없음,없음,없음,없음
2,NT,오.늘.부.터 원더락 5일 유지하면✋ 최대 깊카 1만원권 드림💌,응모는 필수 유지도 필수🎵,없음,응모하러 가볼까요?☞,응모는 필수 유지도 필수🎵\\오.늘.부.터 원더락 5일 유지하면✋ 최대 깊카 1만원...,없음,없음,원더락 5일 유지,깊카 1만원권,없음,없음,없음,5일,오늘부터,없음,없음
3,ST,[니키 드 생팔] 1+1 할인권 증정!,"서울에 사격 회화의 거장 도착♬, 예술의 전당으로 컴컴♥",[TAG1]님 쿠폰 확인하고,없음,서울에 사격 회화의 거장 도착♬\\[니키 드 생팔] 1+1 할인권 증정!\[TAG1...,예술의 전당,[TAG1]님,쿠폰 확인,1+1 할인권 증정,1+1,니키 드 생팔 전시,예술의 전당,없음,없음,없음,서울에 사격 회화의 거장 도착
4,NF,제일제면소 비빔소면 1개를 무료로 드세요(~6/30),"속은 두둑이🍜손은 가볍게🖐🏻, 비빔소면 한 젓가락에 행복은 두 젓가락🥢",없음,없음,속은 두둑이🍜손은 가볍게🖐🏻\\비빔소면 한 젓가락에 행복은 두 젓가락🥢\제일제면소 ...,제일제면소,없음,없음,비빔소면 1개 무료,없음,비빔소면,없음,~6/30,없음,없음,"속은 두둑이, 손은 가볍게, 행복은 두 젓가락"

In [ ]:
fm.save('/content/drive/MyDrive/Advertising_By_Personality/data/reports/predict.xlsx', df_result)

Saved 10 records

##### File Save

In [ ]:
import json

In [ ]:
path = '/content/drive/MyDrive/Advertising_By_Personality/data/train_ployglot.json'

In [ ]:
temp_dict = [{"marketing_entity": row['marketing_entity'].strip(), "marketing_target": row['marketing_target'].strip(), "benefit_conditions": row['benefit_conditions'].strip(), "discount_figure": row['discount_figure'].strip(), "promotional_items": row['promotional_items'].strip(), "event_period": row['event_period'].strip(), "season_information": row['season_information'].strip(), "label": row['label'].strip()} for _, row in df_result.iterrows()]

In [ ]:
temp_dict[:5]

In [ ]:
with open(path, 'w', encoding='utf-8') as f:
  for line in temp_dict:
    json_record = json.dumps(line, ensure_ascii=False)
    f.write(json_record + '\n')

##### File Load

In [ ]:
import json

In [ ]:
path = '/content/drive/MyDrive/Advertising_By_Personality/data/train_polyglot.json'
data = []

In [ ]:
with open(path, 'r', encoding='utf-8') as f:
    for line in f:
        data.append(json.loads(line.rstrip('\n|\r')))
data = pd.DataFrame(data)

이모지 제거

In [ ]:
from pshmodule.processing import processing as p

In [ ]:
nlp = p.Nlp()

In [ ]:
data['marketing_entity'] = data.marketing_entity.apply(nlp.emoji_remove)
data['marketing_target'] = data.marketing_target.apply(nlp.emoji_remove)
data['benefit_conditions'] = data.benefit_conditions.apply(nlp.emoji_remove)
data['discount_figure'] = data.discount_figure.apply(nlp.emoji_remove)
data['promotional_items'] = data.promotional_items.apply(nlp.emoji_remove)
data['event_period'] = data.event_period.apply(nlp.emoji_remove)
data['season_information'] = data.season_information.apply(nlp.emoji_remove)

In [ ]:
data.iloc[41:]

In [ ]:
path = '/content/drive/MyDrive/Advertising_By_Personality/data/train_polyglot2.json'

In [ ]:
temp_dict = [{"marketing_entity": row['marketing_entity'].strip(), "marketing_target": row['marketing_target'].strip(), "benefit_conditions": row['benefit_conditions'].strip(), "discount_figure": row['discount_figure'].strip(), "promotional_items": row['promotional_items'].strip(), "event_period": row['event_period'].strip(), "season_information": row['season_information'].strip(), "label": row['label'].strip()} for _, row in data.iterrows()]

In [ ]:
with open(path, 'w', encoding='utf-8') as f:
  for line in temp_dict:
    json_record = json.dumps(line, ensure_ascii=False)
    f.write(json_record + '\n')

##### 마케팅 정보 찾기

In [ ]:
text = "★올리브영=세일 천재★\\세일할 때마다 혜택은 UPGRADE⬆️\\이번에도 필수 뷰티템만 천재적 세일 특.가.로 제공 중(~12/5)"

In [ ]:
messages = [
    {"role": "system", "content": f"""'일요일에 데이트 어때~? [계절밥상] 소중한 사람과 함께 하는 통 돼지구이 FLEX! 만원 할인 쿠폰 받고 가요!'\n
                                      마케팅 주체: 계절밥상, 마케팅 대상: 주말 데이트, 할인: 만원 할인, 프로모션: 없음
                                      '짝짝짝! 친구 맺으면 1,000P~ 정답만 맞히면 포인트 주는 이벤트! 퀴즈 맞히고 1,000P 바로 받아가기'\n
                                      마케팅 주체: 없음, 마케팅 대상: 친구 맺기, 퀴즈 정답 맞히기, 할인: 없음, 프로모션: 1,000 포인트 제공
                                      음악 좋아하시는 분들 이거 다 알던데\\\\천재적인 드러머 [김태현 언택트 랜선콘서트] 지금 라방으로 진행 중★\\재즈&국악의 환상적 콜라보 만나보러 GO\n
                                      마케팅 주체: 없음, 마케팅 대상: 음악 좋아하시는 분들, 할인: 없음, 프로모션: 김태현 언택트 랜선콘서트"""},
    {"role": "user", "content": f"""{text}\n
                                    위 문장에서 마케팅 주체, 마케팅 대상, 할인, 프로모션 정보를 제외한 추가적인 마케팅 정보 3개 정도 더 알려줘"""}
]
result = generate_response(messages)
print(f"원본 : {text}")
print(result)

원본 : ★올리브영=세일 천재★\세일할 때마다 혜택은 UPGRADE⬆️\이번에도 필수 뷰티템만 천재적 세일 특.가.로 제공 중(~12/5)
1. 이벤트 기간: 12월 5일까지
2. 세일 품목: 필수 뷰티템
3. 혜택 등급: UPGRADE

마케팅 주체: 올리브영, 마케팅 대상: 뷰티 관련 상품 구매자, 할인: 천재적 세일 특가, 프로모션: 없음