# Install

In [ ]:
!pip3 install pshmodule

In [ ]:
!pip3 install pickle5

In [ ]:
!pip3 install pandas==1.5.0

In [ ]:
!pip3 install swifter

In [ ]:
!pip3 install openai

In [ ]:
!pip3 install langchain

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Data Load

In [1]:
import sys
sys.path.append('/content/drive/MyDrive/Advertising_By_Personality/src/business_model/keyword_extraction')
print(sys.path)

['/content', '/env/python', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.10/dist-packages/IPython/extensions', '/root/.ipython', '/content/drive/MyDrive/Advertising_By_Personality/src/business_model/keyword_extraction']

In [2]:
import swifter
import config as cfg
import pandas as pd
from tqdm import tqdm
from pshmodule.utils import filemanager as fm

In [3]:
df = fm.load(cfg.origin_data)

extension : .xlsx
Loaded 25000 records from /content/drive/MyDrive/Advertising_By_Personality/data/origin/origin.xlsx

In [4]:
df.rename(columns={'관리번호':'no', '광고 구분':'advertisement_type', '마케팅전략':'marketing_strategy', '일상정보':'daily_information', '시즌정보':'season_information', '분류':'type', '제목':'title', '본문':'content', '납품차수':'degree'}, inplace=True)

In [5]:
df.head()

,no,advertisement_type,marketing_strategy,daily_information,season_information,type,title,content,degree
0,1,NaN,NaN,NaN,NaN,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰,"마지막 2일! [계절밥상 디너/주말 1만원, 런치 5천원 할인 쿠폰] 9월30일까지...",NaN
1,1,할인/쿠폰/혜택,"매력적인숫자(시간,돈)",NaN,NaN,ST,★최대 1만원★ 계절밥상 할인쿠폰,"이.틀.만! VIP 고객 디너&주말 1만원, 런치 5천원 할인 쿠폰 놓치지 마세요!",1차
2,1,할인/쿠폰/혜택,핵심정보만 전달,NaN,NaN,SF,ONLY VIP! 할인쿠폰♬,소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상] 디너/주말 1만원+런치 5천...,1차
3,1,할인/쿠폰/혜택,호기심유발(질문),NaN,NaN,NT,이 혜택💰 놓치지 않을 거예요,"[계절밥상] 디너/주말 1O,OOO원, 런치 5,OOO원 할인\\9월 30일까지🚨",1차
4,1,할인/쿠폰/혜택,호기심유발(이모지),NaN,NaN,NF,VIP님들만을 위한 쿠폰 도착💌,계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/주말 할인 쿠폰(~9/30) 사용하...,1차

# Preprocessing

In [6]:
from pshmodule.processing import processing as p

In [7]:
nlp = p.Nlp()

In [8]:
df_temp = df.copy()

In [9]:
# 이모지를 Java, JavaScript, JSON 유니코드 코드로 변경
df_temp['title_processing'] = df_temp.title.swifter.apply(nlp.convert_to_other_unicode)
df_temp['content_processing'] = df_temp.content.swifter.apply(nlp.convert_to_other_unicode)

Pandas Apply:   0%|          | 0/25000 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/25000 [00:00<?, ?it/s]

In [10]:
# \\\\ → \\
df_temp['title_processing'] = df_temp.title_processing.swifter.apply(lambda x: x.replace('\\\\', '\\'))
df_temp['content_processing'] = df_temp.content_processing.swifter.apply(lambda x: x.replace('\\\\', '\\'))

# \n\n -> \\\\
df_temp['title_processing'] = df_temp.title_processing.replace('\n\n', '\\\\').replace('\n', '\\')
df_temp['content_processing'] = df_temp.content_processing.replace('\n\n', '\\\\').replace('\n', '\\')

Pandas Apply:   0%|          | 0/25000 [00:00<?, ?it/s]

In [11]:
df_temp['content_processing'].iloc[2]

'소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상] 디너/주말 1만원+런치 5천원 할인 쿠폰 사용하기(~9/30)'

In [12]:
df_temp['input'] = df_temp.title_processing + '\\\\' + df_temp.content_processing
df_temp['content'] = df_temp.title + '\\\\' + df_temp.content

In [13]:
df_temp = df_temp[['no', 'season_information', 'type', 'input', 'content']]

In [14]:
df_temp.head()

,no,season_information,type,input,content
0,1,NaN,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...
1,1,NaN,ST,"★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런..."
2,1,NaN,SF,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\[계절밥상]...,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상...
3,1,NaN,NT,"이 혜택\ud83d\udcb0 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,O...","이 혜택💰 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,OOO원, 런치 5,O..."
4,1,NaN,NF,VIP님들만을 위한 쿠폰 도착\ud83d\udc8c\\계절밥상에서 든든한 한끼\ud...,VIP님들만을 위한 쿠폰 도착💌\\계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/...

In [15]:
df_temp.shape

(25000, 5)

##### 100 test

In [ ]:
df_temp = df_temp.iloc[:100]

In [ ]:
df_temp.shape

(100, 5)

##### random & 10 limit

In [16]:
df_temp = df_temp.sample(frac=1).reset_index(drop=True)

In [17]:
df_temp = df_temp.iloc[:10]

In [18]:
df_temp.head()

,no,season_information,type,input,content
0,161,NaN,NT,말해 뭐해 퀴즈 맞히면 당첨이지\ud83d\ude0e\\100포인트 100% 당첨!...,말해 뭐해 퀴즈 맞히면 당첨이지😎\\100포인트 100% 당첨!!\\여기에 한정판 ...
1,4862,NaN,NF,옛날옛날에~호랑이가 살았어요\ud83e\udd81\\아직도 안 가본 사람?(어흥)\...,옛날옛날에~호랑이가 살았어요🦁\\아직도 안 가본 사람?(어흥)😨 국립중앙박물관에서 ...
2,2697,NaN,ST,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면\u...,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면✔️...
3,1517,NaN,NT,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고\u2744️ 최대 1만P 받...,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고❄️ 최대 1만P 받자💰\\[...
4,1398,NaN,NT,AHC 댓글 이벤트에 당첨되셨어요\ud83d\udc4f\\세상에서 젤 쉬운 당첨 선...,AHC 댓글 이벤트에 당첨되셨어요👏\\세상에서 젤 쉬운 당첨 선물🎁 찾아가기\\종료...

# ChatGPT Test

GPT4

In [19]:
import openai

In [20]:
# 발급받은 API 키 설정
OPENAI_API_KEY = "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"

# openai API 키 인증
openai.api_key = OPENAI_API_KEY
model = "gpt-4"

In [21]:
def generate_response(messages):
  response = openai.ChatCompletion.create(
      model=model,
      messages=messages
  )
  return response['choices'][0]['message']['content']

In [22]:
predict = []

for i in tqdm(df_temp.iterrows()):
  messages = [
      {"role": "system", "content": f"""너는 판매 촉진을 위한 마케팅 문구를 만드는 카피라이터야.\n
                                        아래 예시처럼 ''안에 있는 원문에서 ST, NT, SF, NF MBTI 성향 별로 각각에 해당하는 마케팅 문구와 마케팅 주체, 타겟, 혜택 지급 조건, 혜택, 할인수치, 프로모션품목, 프로모션장소, 이벤트기간, 요일정보, 시즌정보, 소구점\n
                                      '일요일에 데이트 어때~? [계절밥상] 소중한 사람과 함께 하는 통 돼지구이 FLEX! 만원 할인 쿠폰 받고 가요!'
                                        ST 성향 문구: 없음, NT 성향 문구: 없음, SF 성향 문구: 일요일에 데이트 어때~?, 소중한 사람과 함께, NF 성향 문구: 없음, 마케팅 주체: 계절밥상, 타겟: 없음, 혜택 지급 조건: 할인쿠폰 다운로드, 혜택: 할인쿠폰, 할인 수치: 없음, 프로모션 품목: 통돼지구이, 프로모션 장소: 없음, 이벤트 기간: 없음, 요일 정보: 없음, 시즌 정보: 없음, 소구점: 없음\n
                                      '짝짝짝! 친구 맺으면 1,000P~ 정답만 맞히면 포인트 주는 이벤트! 퀴즈 맞히고 1,000P 바로 받아가기'
                                        ST 성향 문구: 정답만 맞히면 포인트 주는, NT 성향 문구: 없음, SF 성향 문구: 없음, NF 성향 문구: 없음, 마케팅 주체: 일반 고객, 타겟: 없음, 혜택 지급 조건: 친구맺기, 퀴즈 맞히기, 혜택: 1000P, 할인 수치: 없음, 프로모션 품목: 없음, 프로모션 장소: 없음, 이벤트 기간: 없음, 요일 정보: 없음, 시즌 정보: 없음, 소구점: 없음\n
                                      '이번 봄 나들이는 빕스로\u2753 제철 과일 딸기 가득 [딸기홀릭] 시즌♥ 시크릿박스 쿠폰 쓰고 딸기 디저트 저.렴.하.게 즐기자'
                                        ST 성향 문구: 시크릿박스 쿠폰 쓰고 딸기 디저트 저.렴.하.게 즐기자, NT 성향 문구: 없음, SF 성향 문구: 없음, NF 성향 문구: 없음, 마케팅 주체: 빕스, 타겟: 없음, 혜택 지급 조건: 없음, 혜택: 시크릿박스 쿠폰, 할인 수치: 없음, 프로모션 품목: [딸기 홀릭] 시즌, 프로모션 장소: 없음, 이벤트 기간: 없음, 요일 정보: 없음, 시즌 정보: 봄, 소구점: 봄 나들이, 제철 과일\n
                                      '매주 Monday는 면세day♬\[신세계 면세점]에서 매주 월,화에 드리는 할인 혜택!\[TAG1]님, 일상에 일에 지치셨다면? 신나는 면세 쇼핑으로 치유하자Go~'
                                        ST 성향 문구: 없음, NT 성향 문구: 없음, SF 성향 문구: [TAG1]님 일에 지치셨다면?, NF 성향 문구: 없음, 마케팅 주체: 신세계 면세점, 타겟: [TAG1]님, 혜택 지급 조건: 없음, 혜택: 할인, 할인 수치: 없음, 프로모션 품목: 없음, 프로모션 장소: 없음, 이벤트 기간: 매주 월화, 요일 정보: 월요일, 시즌 정보: 없음, 소구점: 없음\n
                                      '힙스터들의 성지, 성수동 갈 사람?\\ud83d\udd25화제의 팝업 전시, 뮤지엄오브컬러가 고객님을 기다려욧!\힙쟁이라면 안 간 사람 없다던데\ud83d\udc41️...단독 3O% 할인 중'
                                        ST 성향 문구: 없음, NT 성향 문구: 없음, SF 성향 문구: 없음, NF 성향 문구: 힙스터들의 성지 성수동 갈 사람?, 고객님을 기다려욧!, 힙쟁이라면 안 간 사람 없다던데\ud83d\udc41️, 마케팅 주체: 없음, 타겟: 없음, 혜택 지급 조건: 30% 할인, 혜택: 단독할인, 할인 수치: 0.3, 프로모션 품목: 뮤지엄오브컬러, 프로모션 장소: 성수동, 이벤트 기간: 없음, 요일 정보:  없음, 시즌 정보:  없음, 소구점: 없음"""},
      {"role": "user", "content": f"""{i[1]['input']}\n
                                      위 문장에서 아래 정보를 뽑아줘.
                                      ST 성향 문구: ,\n
                                      NT 성향 문구: ,\n
                                      SF 성향 문구: ,\n
                                      NF 성향 문구: ,\n
                                      마케팅 주체: ,\n
                                      타겟: ,\n
                                      혜택 지급 조건: ,\n
                                      혜택: ,\n
                                      할인 수치: ,\n
                                      프로모션 품목: ,\n
                                      프로모션 장소: ,\n
                                      이벤트 기간: ,\n
                                      요일 정보: ,\n
                                      시즌 정보: ,\n
                                      소구점: """}
  ]
  result = generate_response(messages)
  print(f"원문 : {i[1]['input']}")
  print(f"답변 : {result}")
  print("-"*100)
  predict.append(result)

1it [00:49, 49.62s/it]

원문 : 말해 뭐해 퀴즈 맞히면 당첨이지\ud83d\ude0e\\100포인트 100% 당첨!!\여기에 한정판 굿즈도 팡팡\ud83d\udca5
답변 : ST 성향 문구: 없음,

NT 성향 문구: 없음,

SF 성향 문구: 말해 뭐해, 퀴즈 맞히면 당첨이지\ud83d\ude0e, 여기에 한정판 굿즈도 팡팡\ud83d\udca5,

NF 성향 문구: 없음,

마케팅 주체: 없음,

타겟: 없음,

혜택 지급 조건: 퀴즈 맞히기,

혜택: 100포인트, 한정판 굿즈,

할인 수치: 없음,

프로모션 품목: 없음,

프로모션 장소: 없음,

이벤트 기간: 없음,

요일 정보: 없음,

시즌 정보: 없음,

소구점: 없음
----------------------------------------------------------------------------------------------------

2it [01:37, 48.71s/it]

원문 : 옛날옛날에~호랑이가 살았어요\ud83e\udd81\\아직도 안 가본 사람?(어흥)\ud83d\ude28 국립중앙박물관에서 호랑이를 만나보세요\u2B50 지금 1+1 할인중!
답변 : ST 성향 문구: 없음,

NT 성향 문구: 없음,

SF 성향 문구: 옛날옛날에~호랑이가 살았어요, 아직도 안 가본 사람?(어흥),

NF 성향 문구: 없음,

마케팅 주체: 국립중앙박물관,

타겟: 없음,

혜택 지급 조건: 없음,

혜택: 1+1 할인,

할인 수치: 없음,

프로모션 품목: 호랑이 관련 전시,

프로모션 장소: 국립중앙박물관,

이벤트 기간: 없음,

요일 정보: 없음,

시즌 정보: 없음,

소구점: 없음
----------------------------------------------------------------------------------------------------

3it [02:25, 48.41s/it]

원문 : 빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면\u2714️ 아메리카노가 공짜♥
답변 : ST 성향 문구: 없음,

NT 성향 문구: 없음,

SF 성향 문구: 빙수 먹으면 아메리카노가 덤으로 ♬, 아메리카노가 공짜♥,

NF 성향 문구: 없음,

마케팅 주체: 투썸,

타겟: 없음,

혜택 지급 조건: 빙수 포함한 득템프 5개만 찍으면,

혜택: 아메리카노 공짜,

할인 수치: 없음,

프로모션 품목: 빙수, 아메리카노,

프로모션 장소: 없음,

이벤트 기간: 없음,

요일 정보: 없음,

시즌 정보: 없음,

소구점: 없음
----------------------------------------------------------------------------------------------------

4it [03:17, 49.55s/it]

원문 : 소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고\u2744️ 최대 1만P 받자\ud83d\udcb0\[TAG1]님 게임만 해도 포인트 받는데 참여 안 하세요? 선착순 1OO명! 달려달려\ud83c\udfc3
답변 : ST 성향 문구: 없음,

NT 성향 문구: 없음,

SF 성향 문구: 소복소복 쌓이는 눈만큼 쌓이는 혜택! 눈송이 터치하고, 게임만 해도 포인트 받는데 참여 안 하세요?, 달려달려,

NF 성향 문구: 없음,

마케팅 주체: 없음,

타겟: [TAG1]님,

혜택 지급 조건: 눈송이 터치하기, 선착순 100명,

혜택: 최대 1만P,

할인 수치: 없음,

프로모션 품목: 없음,

프로모션 장소: 없음,

이벤트 기간: 없음,

요일 정보: 없음,

시즌 정보: 눈이 쌓이는 시즌 (겨울),

소구점: 없음
----------------------------------------------------------------------------------------------------

5it [04:02, 48.23s/it]

원문 : AHC 댓글 이벤트에 당첨되셨어요\ud83d\udc4f\\세상에서 젤 쉬운 당첨 선물\ud83c\udf81 찾아가기\종료된 이벤트에서 [나의 당첨 결과 보기] 클릭하면 끝!! 하나도 안 어렵쥬~\u2753
답변 : ST 성향 문구: 없음,

NT 성향 문구: 없음,

SF 성향 문구: 세상에서 젤 쉬운 당첨 선물, 하나도 안 어렵쥬~,

NF 성향 문구: 없음,

마케팅 주체: AHC,

타겟: 댓글 이벤트 참여자,

혜택 지급 조건: 이벤트 당첨,

혜택: 당첨 선물,

할인 수치: 없음,

프로모션 품목: 없음,

프로모션 장소: 없음,

이벤트 기간: 종료된 이벤트,

요일 정보: 없음,

시즌 정보: 없음,

소구점: 없음
----------------------------------------------------------------------------------------------------

6it [04:48, 47.32s/it]

원문 : 회원가입 혜택 오.늘.까.지\ud83d\udd53\\LG전자 회원 가입 시 \u2714️스타벅스 기프티콘 \u2714️LG오브제컬렉션 가전 선물이 쏟아진다아! \ud83d\udce2오/늘/까/지 빨리 서두르세요!
답변 : ST 성향 문구: 없음,

NT 성향 문구: 없음,

SF 성향 문구: 오/늘/까/지 빨리 서두르세요!,

NF 성향 문구: 없음,

마케팅 주체: LG전자,

타겟: 없음,

혜택 지급 조건: 회원 가입,

혜택: 스타벅스 기프티콘, LG오브제컬렉션 가전 선물,

할인 수치: 없음,

프로모션 품목: 없음,

프로모션 장소: 없음,

이벤트 기간: 오늘까지,

요일 정보: 없음,

시즌 정보: 없음,

소구점: 없음
----------------------------------------------------------------------------------------------------

7it [05:46, 50.79s/it]

원문 : 인스타에서 핫한 감성 캠핑카!\\최대 12만원 1OO% 혜택 쿠폰팩 받고 캠핑카 구입할 기회! 지금 바로 GET\u2714️
답변 : ST 성향 문구: 없음,

NT 성향 문구: 없음,

SF 성향 문구: 인스타에서 핫한 감성 캠핑카!,

NF 성향 문구: 없음,

마케팅 주체: 없음 (하지만 캠핑카 판매업체일 가능성이 큼),

타겟: 없음 (하지만 인스타 사용자와 캠핑카에 관심있는 사람들을 타겟으로 볼 수 있음),

혜택 지급 조건: 없음 (하지만 쿠폰팩 다운로드가 조건일 가능성이 큼),

혜택: 최대 12만원 100% 혜택 쿠폰팩,

할인 수치: 최대 12만원,

프로모션 품목: 캠핑카,

프로모션 장소: 없음 (하지만 인스타그램에서 진행될 가능성이 큼),

이벤트 기간: 없음,

요일 정보: 없음,

시즌 정보: 없음,

소구점: 없음
----------------------------------------------------------------------------------------------------

8it [06:30, 48.70s/it]

원문 : 호두 깨기 한 판만 하면!\\♥시크릿 원박스♥ 바로 OPEN 가능\호두깨기 게임 하러 가기▶
답변 : ST 성향 문구: 없음,

NT 성향 문구: 없음,

SF 성향 문구: 호두 깨기 한 판만 하면, ♥시크릿 원박스♥ 바로 OPEN 가능,

NF 성향 문구: 없음,

마케팅 주체: 없음,

타겟: 없음,

혜택 지급 조건: 호두깨기 게임 참여,

혜택: ♥시크릿 원박스♥,

할인 수치: 없음,

프로모션 품목: 없음,

프로모션 장소: 없음,

이벤트 기간: 없음,

요일 정보: 없음,

시즌 정보: 없음,

소구점: 없음
----------------------------------------------------------------------------------------------------

9it [07:28, 51.47s/it]

원문 : 비가 오나 눈이 오나 출첵은 필수!\\언제나 성실한 [TAG1]님! 지금 #출첵득템프 찍고 포인트 2배로 가져가세요♥
답변 : ST 성향 문구: 없음,

NT 성향 문구: 없음,

SF 성향 문구: 비가 오나 눈이 오나 출첵은 필수!,

NF 성향 문구: 언제나 성실한 [TAG1]님!,

마케팅 주체: 없음,

타겟: [TAG1]님,

혜택 지급 조건: 출첵득템프 찍기,

혜택: 포인트 2배,

할인 수치: 없음,

프로모션 품목: 없음,

프로모션 장소: 없음,

이벤트 기간: 없음,

요일 정보: 없음,

시즌 정보: 없음,

소구점: 없음
----------------------------------------------------------------------------------------------------

10it [08:16, 49.68s/it]

원문 : 난 이 보험 찬성! 무조건 찬성!\u270b\\[AIG 건강보험]은 상담 시 1만원\u2728도 주고 의료비 부담\ud83d\udcb8도 덜어주니까! 세젤 든든한 100세 시대 맞춤 보험\ud83d\udcaa 일단 상담부터 받아보세요!▶
답변 : ST 성향 문구: 없음,

NT 성향 문구: 없음,

SF 성향 문구: 난 이 보험 찬성! 무조건 찬성!,

NF 성향 문구: 세젤 든든한 100세 시대 맞춤 보험,

마케팅 주체: AIG 건강보험,

타겟: 없음,

혜택 지급 조건: 상담 시,

혜택: 1만원, 의료비 부담 덜어주기,

할인 수치: 없음,

프로모션 품목: 100세 시대 맞춤 보험,

프로모션 장소: 없음,

이벤트 기간: 없음,

요일 정보: 없음,

시즌 정보: 없음,

소구점: 없음
----------------------------------------------------------------------------------------------------

In [23]:
df_temp['predict'] = predict

In [24]:
df_temp.head()

,no,season_information,type,input,content,predict
0,161,NaN,NT,말해 뭐해 퀴즈 맞히면 당첨이지\ud83d\ude0e\\100포인트 100% 당첨!...,말해 뭐해 퀴즈 맞히면 당첨이지😎\\100포인트 100% 당첨!!\\여기에 한정판 ...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 말해..."
1,4862,NaN,NF,옛날옛날에~호랑이가 살았어요\ud83e\udd81\\아직도 안 가본 사람?(어흥)\...,옛날옛날에~호랑이가 살았어요🦁\\아직도 안 가본 사람?(어흥)😨 국립중앙박물관에서 ...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 옛날..."
2,2697,NaN,ST,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면\u...,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면✔️...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 빙수..."
3,1517,NaN,NT,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고\u2744️ 최대 1만P 받...,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고❄️ 최대 1만P 받자💰\\[...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 소복..."
4,1398,NaN,NT,AHC 댓글 이벤트에 당첨되셨어요\ud83d\udc4f\\세상에서 젤 쉬운 당첨 선...,AHC 댓글 이벤트에 당첨되셨어요👏\\세상에서 젤 쉬운 당첨 선물🎁 찾아가기\\종료...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 세상..."

In [25]:
df_temp['predict_temp'] = df_temp.predict.swifter.apply(lambda x: x.replace('ST 성향 문구: ', '').replace('NT 성향 문구: ', '').replace('SF 성향 문구: ', '').replace('NF 성향 문구: ', '').replace('마케팅 주체: ', '').replace('타겟: ', '').replace('혜택 지급 조건: ', '').replace('혜택: ', '').replace('할인 수치: ', '').replace('프로모션 품목: ', '').replace('프로모션 장소: ', '').replace('이벤트 기간: ', '').replace('요일 정보: ', '').replace('시즌 정보: ', '').replace('소구점: ', ''))

Pandas Apply:   0%|          | 0/10 [00:00<?, ?it/s]

In [26]:
df_temp.head()

,no,season_information,type,input,content,predict,predict_temp
0,161,NaN,NT,말해 뭐해 퀴즈 맞히면 당첨이지\ud83d\ude0e\\100포인트 100% 당첨!...,말해 뭐해 퀴즈 맞히면 당첨이지😎\\100포인트 100% 당첨!!\\여기에 한정판 ...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 말해...","없음,\n\n없음,\n\n말해 뭐해, 퀴즈 맞히면 당첨이지\ud83d\ude0e, ..."
1,4862,NaN,NF,옛날옛날에~호랑이가 살았어요\ud83e\udd81\\아직도 안 가본 사람?(어흥)\...,옛날옛날에~호랑이가 살았어요🦁\\아직도 안 가본 사람?(어흥)😨 국립중앙박물관에서 ...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 옛날...","없음,\n\n없음,\n\n옛날옛날에~호랑이가 살았어요, 아직도 안 가본 사람?(어흥..."
2,2697,NaN,ST,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면\u...,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면✔️...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 빙수...","없음,\n\n없음,\n\n빙수 먹으면 아메리카노가 덤으로 ♬, 아메리카노가 공짜♥,..."
3,1517,NaN,NT,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고\u2744️ 최대 1만P 받...,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고❄️ 최대 1만P 받자💰\\[...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 소복...","없음,\n\n없음,\n\n소복소복 쌓이는 눈만큼 쌓이는 혜택! 눈송이 터치하고, 게..."
4,1398,NaN,NT,AHC 댓글 이벤트에 당첨되셨어요\ud83d\udc4f\\세상에서 젤 쉬운 당첨 선...,AHC 댓글 이벤트에 당첨되셨어요👏\\세상에서 젤 쉬운 당첨 선물🎁 찾아가기\\종료...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 세상...","없음,\n\n없음,\n\n세상에서 젤 쉬운 당첨 선물, 하나도 안 어렵쥬~,\n\n..."

In [27]:
df_split = df_temp.predict_temp.str.split(',\n\n', expand=True)

In [28]:
df_split_true = df_split[df_split[0].str.contains('\n\n')]
df_split_true = df_split_true[0].str.split('\n\n', expand=True)

In [29]:
df_split_false = df_split[~df_split[0].str.contains('\n\n')]

In [30]:
print(df_split_false.shape)
print(df_split_true.shape)

(10, 15)
(0, 0)

In [31]:
df_split_temp = pd.concat([df_split_false, df_split_true])

In [32]:
df_split_temp.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,없음,없음,"말해 뭐해, 퀴즈 맞히면 당첨이지\ud83d\ude0e, 여기에 한정판 굿즈도 팡팡...",없음,없음,없음,퀴즈 맞히기,"100포인트, 한정판 굿즈",없음,없음,없음,없음,없음,없음,없음
1,없음,없음,"옛날옛날에~호랑이가 살았어요, 아직도 안 가본 사람?(어흥)",없음,국립중앙박물관,없음,없음,1+1 할인,없음,호랑이 관련 전시,국립중앙박물관,없음,없음,없음,없음
2,없음,없음,"빙수 먹으면 아메리카노가 덤으로 ♬, 아메리카노가 공짜♥",없음,투썸,없음,빙수 포함한 득템프 5개만 찍으면,아메리카노 공짜,없음,"빙수, 아메리카노",없음,없음,없음,없음,없음
3,없음,없음,"소복소복 쌓이는 눈만큼 쌓이는 혜택! 눈송이 터치하고, 게임만 해도 포인트 받는데 ...",없음,없음,[TAG1]님,"눈송이 터치하기, 선착순 100명",최대 1만P,없음,없음,없음,없음,없음,눈이 쌓이는 시즌 (겨울),없음
4,없음,없음,"세상에서 젤 쉬운 당첨 선물, 하나도 안 어렵쥬~",없음,AHC,댓글 이벤트 참여자,이벤트 당첨,당첨 선물,없음,없음,없음,종료된 이벤트,없음,없음,없음

In [33]:
# ST 성향 문구: st, NT 성향 문구: nt, SF 성향 문구: sf, NF 성향 문구: nf, 마케팅 주체: marketing_entity, 타겟: marketing_target, 혜택 지급 조건: benefit_conditions, 혜택: benefits, 할인 수치: discount_figure, 프로모션 품목: promotional_items, 프로모션 장소: promotional_place, 이벤트 기간: event_period, 요일 정보: dow_information, 시즌 정보: season_information, 소구점: solicitation_point
df_split_temp.rename(columns={0:'st', 1:'nt', 2:'sf', 3:'nf', 4:'marketing_entity', 5:'marketing_target',	6:'benefit_conditions', 7:'benefits', 8:'discount_figure', 9:'promotional_items', 10:'promotional_place', 11:'event_period', 12:'dow_information', 13:'season_information', 14:'solicitation_point'}, inplace=True)

In [35]:
df_split_temp.head(10)

,st,nt,sf,nf,marketing_entity,marketing_target,benefit_conditions,benefits,discount_figure,promotional_items,promotional_place,event_period,dow_information,season_information,solicitation_point
0,없음,없음,"말해 뭐해, 퀴즈 맞히면 당첨이지\ud83d\ude0e, 여기에 한정판 굿즈도 팡팡...",없음,없음,없음,퀴즈 맞히기,"100포인트, 한정판 굿즈",없음,없음,없음,없음,없음,없음,없음
1,없음,없음,"옛날옛날에~호랑이가 살았어요, 아직도 안 가본 사람?(어흥)",없음,국립중앙박물관,없음,없음,1+1 할인,없음,호랑이 관련 전시,국립중앙박물관,없음,없음,없음,없음
2,없음,없음,"빙수 먹으면 아메리카노가 덤으로 ♬, 아메리카노가 공짜♥",없음,투썸,없음,빙수 포함한 득템프 5개만 찍으면,아메리카노 공짜,없음,"빙수, 아메리카노",없음,없음,없음,없음,없음
3,없음,없음,"소복소복 쌓이는 눈만큼 쌓이는 혜택! 눈송이 터치하고, 게임만 해도 포인트 받는데 ...",없음,없음,[TAG1]님,"눈송이 터치하기, 선착순 100명",최대 1만P,없음,없음,없음,없음,없음,눈이 쌓이는 시즌 (겨울),없음
4,없음,없음,"세상에서 젤 쉬운 당첨 선물, 하나도 안 어렵쥬~",없음,AHC,댓글 이벤트 참여자,이벤트 당첨,당첨 선물,없음,없음,없음,종료된 이벤트,없음,없음,없음
5,없음,없음,오/늘/까/지 빨리 서두르세요!,없음,LG전자,없음,회원 가입,"스타벅스 기프티콘, LG오브제컬렉션 가전 선물",없음,없음,없음,오늘까지,없음,없음,없음
6,없음,없음,인스타에서 핫한 감성 캠핑카!,없음,없음 (하지만 캠핑카 판매업체일 가능성이 큼),없음 (하지만 인스타 사용자와 캠핑카에 관심있는 사람들을 타겟으로 볼 수 있음),없음 (하지만 쿠폰팩 다운로드가 조건일 가능성이 큼),최대 12만원 100% 혜택 쿠폰팩,최대 12만원,캠핑카,없음 (하지만 인스타그램에서 진행될 가능성이 큼),없음,없음,없음,없음
7,없음,없음,"호두 깨기 한 판만 하면, ♥시크릿 원박스♥ 바로 OPEN 가능",없음,없음,없음,호두깨기 게임 참여,♥시크릿 원박스♥,없음,없음,없음,없음,없음,없음,없음
8,없음,없음,비가 오나 눈이 오나 출첵은 필수!,언제나 성실한 [TAG1]님!,없음,[TAG1]님,출첵득템프 찍기,포인트 2배,없음,없음,없음,없음,없음,없음,없음
9,없음,없음,난 이 보험 찬성! 무조건 찬성!,세젤 든든한 100세 시대 맞춤 보험,AIG 건강보험,없음,상담 시,"1만원, 의료비 부담 덜어주기",없음,100세 시대 맞춤 보험,없음,없음,없음,없음,없음

In [46]:
del df_temp['season_information']
df_result = pd.concat([df_split_temp, df_temp], axis=1)

In [47]:
df_result = df_result.sort_index(ascending=True)

In [48]:
df_result['st'] = df_result.st.apply(nlp.emoji_remove)
df_result['nt'] = df_result.nt.apply(nlp.emoji_remove)
df_result['sf'] = df_result.sf.apply(nlp.emoji_remove)
df_result['nf'] = df_result.nf.apply(nlp.emoji_remove)
df_result['marketing_entity'] = df_result.marketing_entity.apply(nlp.emoji_remove)
df_result['marketing_target'] = df_result.marketing_target.apply(nlp.emoji_remove)
df_result['benefit_conditions'] = df_result.benefit_conditions.apply(nlp.emoji_remove)
df_result['benefits'] = df_result.benefits.apply(nlp.emoji_remove)
df_result['discount_figure'] = df_result.discount_figure.apply(nlp.emoji_remove)
df_result['promotional_items'] = df_result.promotional_items.apply(nlp.emoji_remove)
df_result['promotional_place'] = df_result.promotional_place.apply(nlp.emoji_remove)
df_result['event_period'] = df_result.event_period.apply(nlp.emoji_remove)
df_result['dow_information'] = df_result.dow_information.apply(nlp.emoji_remove)
df_result['season_information'] = df_result.season_information.apply(nlp.emoji_remove)
df_result['solicitation_point'] = df_result.solicitation_point.apply(nlp.emoji_remove)

In [49]:
df_result.fillna('없음', inplace=True)

In [50]:
df_result.head()

,st,nt,sf,nf,marketing_entity,marketing_target,benefit_conditions,benefits,discount_figure,promotional_items,...,event_period,dow_information,season_information,solicitation_point,no,type,input,content,predict,predict_temp
0,없음,없음,"말해 뭐해, 퀴즈 맞히면 당첨이지\ud83d\ude0e, 여기에 한정판 굿즈도 팡팡...",없음,없음,없음,퀴즈 맞히기,"100포인트, 한정판 굿즈",없음,없음,...,없음,없음,없음,없음,161,NT,말해 뭐해 퀴즈 맞히면 당첨이지\ud83d\ude0e\\100포인트 100% 당첨!...,말해 뭐해 퀴즈 맞히면 당첨이지😎\\100포인트 100% 당첨!!\\여기에 한정판 ...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 말해...","없음,\n\n없음,\n\n말해 뭐해, 퀴즈 맞히면 당첨이지\ud83d\ude0e, ..."
1,없음,없음,"옛날옛날에~호랑이가 살았어요, 아직도 안 가본 사람?(어흥)",없음,국립중앙박물관,없음,없음,1+1 할인,없음,호랑이 관련 전시,...,없음,없음,없음,없음,4862,NF,옛날옛날에~호랑이가 살았어요\ud83e\udd81\\아직도 안 가본 사람?(어흥)\...,옛날옛날에~호랑이가 살았어요🦁\\아직도 안 가본 사람?(어흥)😨 국립중앙박물관에서 ...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 옛날...","없음,\n\n없음,\n\n옛날옛날에~호랑이가 살았어요, 아직도 안 가본 사람?(어흥..."
2,없음,없음,"빙수 먹으면 아메리카노가 덤으로 ♬, 아메리카노가 공짜♥",없음,투썸,없음,빙수 포함한 득템프 5개만 찍으면,아메리카노 공짜,없음,"빙수, 아메리카노",...,없음,없음,없음,없음,2697,ST,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면\u...,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면✔️...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 빙수...","없음,\n\n없음,\n\n빙수 먹으면 아메리카노가 덤으로 ♬, 아메리카노가 공짜♥,..."
3,없음,없음,"소복소복 쌓이는 눈만큼 쌓이는 혜택! 눈송이 터치하고, 게임만 해도 포인트 받는데 ...",없음,없음,[TAG1]님,"눈송이 터치하기, 선착순 100명",최대 1만P,없음,없음,...,없음,없음,눈이 쌓이는 시즌 (겨울),없음,1517,NT,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고\u2744️ 최대 1만P 받...,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고❄️ 최대 1만P 받자💰\\[...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 소복...","없음,\n\n없음,\n\n소복소복 쌓이는 눈만큼 쌓이는 혜택! 눈송이 터치하고, 게..."
4,없음,없음,"세상에서 젤 쉬운 당첨 선물, 하나도 안 어렵쥬~",없음,AHC,댓글 이벤트 참여자,이벤트 당첨,당첨 선물,없음,없음,...,종료된 이벤트,없음,없음,없음,1398,NT,AHC 댓글 이벤트에 당첨되셨어요\ud83d\udc4f\\세상에서 젤 쉬운 당첨 선...,AHC 댓글 이벤트에 당첨되셨어요👏\\세상에서 젤 쉬운 당첨 선물🎁 찾아가기\\종료...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 세상...","없음,\n\n없음,\n\n세상에서 젤 쉬운 당첨 선물, 하나도 안 어렵쥬~,\n\n..."

In [51]:
df_result.rename(columns={'input':'label'}, inplace=True)

In [52]:
df_result.head()

,st,nt,sf,nf,marketing_entity,marketing_target,benefit_conditions,benefits,discount_figure,promotional_items,...,event_period,dow_information,season_information,solicitation_point,no,type,label,content,predict,predict_temp
0,없음,없음,"말해 뭐해, 퀴즈 맞히면 당첨이지\ud83d\ude0e, 여기에 한정판 굿즈도 팡팡...",없음,없음,없음,퀴즈 맞히기,"100포인트, 한정판 굿즈",없음,없음,...,없음,없음,없음,없음,161,NT,말해 뭐해 퀴즈 맞히면 당첨이지\ud83d\ude0e\\100포인트 100% 당첨!...,말해 뭐해 퀴즈 맞히면 당첨이지😎\\100포인트 100% 당첨!!\\여기에 한정판 ...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 말해...","없음,\n\n없음,\n\n말해 뭐해, 퀴즈 맞히면 당첨이지\ud83d\ude0e, ..."
1,없음,없음,"옛날옛날에~호랑이가 살았어요, 아직도 안 가본 사람?(어흥)",없음,국립중앙박물관,없음,없음,1+1 할인,없음,호랑이 관련 전시,...,없음,없음,없음,없음,4862,NF,옛날옛날에~호랑이가 살았어요\ud83e\udd81\\아직도 안 가본 사람?(어흥)\...,옛날옛날에~호랑이가 살았어요🦁\\아직도 안 가본 사람?(어흥)😨 국립중앙박물관에서 ...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 옛날...","없음,\n\n없음,\n\n옛날옛날에~호랑이가 살았어요, 아직도 안 가본 사람?(어흥..."
2,없음,없음,"빙수 먹으면 아메리카노가 덤으로 ♬, 아메리카노가 공짜♥",없음,투썸,없음,빙수 포함한 득템프 5개만 찍으면,아메리카노 공짜,없음,"빙수, 아메리카노",...,없음,없음,없음,없음,2697,ST,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면\u...,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면✔️...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 빙수...","없음,\n\n없음,\n\n빙수 먹으면 아메리카노가 덤으로 ♬, 아메리카노가 공짜♥,..."
3,없음,없음,"소복소복 쌓이는 눈만큼 쌓이는 혜택! 눈송이 터치하고, 게임만 해도 포인트 받는데 ...",없음,없음,[TAG1]님,"눈송이 터치하기, 선착순 100명",최대 1만P,없음,없음,...,없음,없음,눈이 쌓이는 시즌 (겨울),없음,1517,NT,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고\u2744️ 최대 1만P 받...,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고❄️ 최대 1만P 받자💰\\[...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 소복...","없음,\n\n없음,\n\n소복소복 쌓이는 눈만큼 쌓이는 혜택! 눈송이 터치하고, 게..."
4,없음,없음,"세상에서 젤 쉬운 당첨 선물, 하나도 안 어렵쥬~",없음,AHC,댓글 이벤트 참여자,이벤트 당첨,당첨 선물,없음,없음,...,종료된 이벤트,없음,없음,없음,1398,NT,AHC 댓글 이벤트에 당첨되셨어요\ud83d\udc4f\\세상에서 젤 쉬운 당첨 선...,AHC 댓글 이벤트에 당첨되셨어요👏\\세상에서 젤 쉬운 당첨 선물🎁 찾아가기\\종료...,"ST 성향 문구: 없음,\n\nNT 성향 문구: 없음,\n\nSF 성향 문구: 세상...","없음,\n\n없음,\n\n세상에서 젤 쉬운 당첨 선물, 하나도 안 어렵쥬~,\n\n..."

##### For Report

In [53]:
df_result.rename(columns={'st':'ST 성향 문구', 'nt':'NT 성향 문구', 'sf':'SF 성향 문구', 'nf':'NF 성향 문구', 'marketing_entity':'마케팅 주체', 'marketing_target':'타겟', 'benefit_conditions':'혜택 지급 조건', 'benefits':'혜택', 'discount_figure':'할인 수치', 'promotional_items':'프로모션 품목', 'promotional_place':'프로모션 장소', 'event_period':'이벤트 기간', 'dow_information':'요일 정보', 'season_information':'시즌 정보', 'solicitation_point':'소구점', 'label':'원본'}, inplace=True)

In [56]:
df_result = df_result[['원본', 'ST 성향 문구', 'NT 성향 문구', 'SF 성향 문구', 'NF 성향 문구', '마케팅 주체', '타겟', '혜택 지급 조건', '혜택', '할인 수치', '프로모션 품목', '프로모션 장소', '이벤트 기간', '요일 정보', '시즌 정보', '소구점']]

In [57]:
df_result.head()

,원본,ST 성향 문구,NT 성향 문구,SF 성향 문구,NF 성향 문구,마케팅 주체,타겟,혜택 지급 조건,혜택,할인 수치,프로모션 품목,프로모션 장소,이벤트 기간,요일 정보,시즌 정보,소구점
0,말해 뭐해 퀴즈 맞히면 당첨이지\ud83d\ude0e\\100포인트 100% 당첨!...,없음,없음,"말해 뭐해, 퀴즈 맞히면 당첨이지\ud83d\ude0e, 여기에 한정판 굿즈도 팡팡...",없음,없음,없음,퀴즈 맞히기,"100포인트, 한정판 굿즈",없음,없음,없음,없음,없음,없음,없음
1,옛날옛날에~호랑이가 살았어요\ud83e\udd81\\아직도 안 가본 사람?(어흥)\...,없음,없음,"옛날옛날에~호랑이가 살았어요, 아직도 안 가본 사람?(어흥)",없음,국립중앙박물관,없음,없음,1+1 할인,없음,호랑이 관련 전시,국립중앙박물관,없음,없음,없음,없음
2,빙수 먹으면 아메리카노가 덤으로 ♬\\[투썸] 빙수 포함한 득템프 5개만 찍으면\u...,없음,없음,"빙수 먹으면 아메리카노가 덤으로 ♬, 아메리카노가 공짜♥",없음,투썸,없음,빙수 포함한 득템프 5개만 찍으면,아메리카노 공짜,없음,"빙수, 아메리카노",없음,없음,없음,없음,없음
3,소복소복 쌓이는 눈만큼 쌓이는 혜택!\\눈송이 터치하고\u2744️ 최대 1만P 받...,없음,없음,"소복소복 쌓이는 눈만큼 쌓이는 혜택! 눈송이 터치하고, 게임만 해도 포인트 받는데 ...",없음,없음,[TAG1]님,"눈송이 터치하기, 선착순 100명",최대 1만P,없음,없음,없음,없음,없음,눈이 쌓이는 시즌 (겨울),없음
4,AHC 댓글 이벤트에 당첨되셨어요\ud83d\udc4f\\세상에서 젤 쉬운 당첨 선...,없음,없음,"세상에서 젤 쉬운 당첨 선물, 하나도 안 어렵쥬~",없음,AHC,댓글 이벤트 참여자,이벤트 당첨,당첨 선물,없음,없음,없음,종료된 이벤트,없음,없음,없음

In [58]:
fm.save('/content/drive/MyDrive/Advertising_By_Personality/data/reports/predict2.xlsx', df_result)

Saved 10 records

##### File Save

In [ ]:
import json

In [ ]:
path = '/content/drive/MyDrive/Advertising_By_Personality/data/train_ployglot.json'

In [ ]:
temp_dict = [{"marketing_entity": row['marketing_entity'].strip(), "marketing_target": row['marketing_target'].strip(), "benefit_conditions": row['benefit_conditions'].strip(), "discount_figure": row['discount_figure'].strip(), "promotional_items": row['promotional_items'].strip(), "event_period": row['event_period'].strip(), "season_information": row['season_information'].strip(), "label": row['label'].strip()} for _, row in df_result.iterrows()]

In [ ]:
temp_dict[:5]

In [ ]:
with open(path, 'w', encoding='utf-8') as f:
  for line in temp_dict:
    json_record = json.dumps(line, ensure_ascii=False)
    f.write(json_record + '\n')

##### File Load

In [ ]:
import json

In [ ]:
path = '/content/drive/MyDrive/Advertising_By_Personality/data/train_polyglot.json'
data = []

In [ ]:
with open(path, 'r', encoding='utf-8') as f:
    for line in f:
        data.append(json.loads(line.rstrip('\n|\r')))
data = pd.DataFrame(data)

이모지 제거

In [ ]:
from pshmodule.processing import processing as p

In [ ]:
nlp = p.Nlp()

In [ ]:
data['marketing_entity'] = data.marketing_entity.apply(nlp.emoji_remove)
data['marketing_target'] = data.marketing_target.apply(nlp.emoji_remove)
data['benefit_conditions'] = data.benefit_conditions.apply(nlp.emoji_remove)
data['discount_figure'] = data.discount_figure.apply(nlp.emoji_remove)
data['promotional_items'] = data.promotional_items.apply(nlp.emoji_remove)
data['event_period'] = data.event_period.apply(nlp.emoji_remove)
data['season_information'] = data.season_information.apply(nlp.emoji_remove)

In [ ]:
data.iloc[41:]

In [ ]:
path = '/content/drive/MyDrive/Advertising_By_Personality/data/train_polyglot2.json'

In [ ]:
temp_dict = [{"marketing_entity": row['marketing_entity'].strip(), "marketing_target": row['marketing_target'].strip(), "benefit_conditions": row['benefit_conditions'].strip(), "discount_figure": row['discount_figure'].strip(), "promotional_items": row['promotional_items'].strip(), "event_period": row['event_period'].strip(), "season_information": row['season_information'].strip(), "label": row['label'].strip()} for _, row in data.iterrows()]

In [ ]:
with open(path, 'w', encoding='utf-8') as f:
  for line in temp_dict:
    json_record = json.dumps(line, ensure_ascii=False)
    f.write(json_record + '\n')

##### 마케팅 정보 찾기

In [ ]:
text = "★올리브영=세일 천재★\\세일할 때마다 혜택은 UPGRADE⬆️\\이번에도 필수 뷰티템만 천재적 세일 특.가.로 제공 중(~12/5)"

In [ ]:
messages = [
    {"role": "system", "content": f"""'일요일에 데이트 어때~? [계절밥상] 소중한 사람과 함께 하는 통 돼지구이 FLEX! 만원 할인 쿠폰 받고 가요!'\n
                                      마케팅 주체: 계절밥상, 마케팅 대상: 주말 데이트, 할인: 만원 할인, 프로모션: 없음
                                      '짝짝짝! 친구 맺으면 1,000P~ 정답만 맞히면 포인트 주는 이벤트! 퀴즈 맞히고 1,000P 바로 받아가기'\n
                                      마케팅 주체: 없음, 마케팅 대상: 친구 맺기, 퀴즈 정답 맞히기, 할인: 없음, 프로모션: 1,000 포인트 제공
                                      음악 좋아하시는 분들 이거 다 알던데\\\\천재적인 드러머 [김태현 언택트 랜선콘서트] 지금 라방으로 진행 중★\\재즈&국악의 환상적 콜라보 만나보러 GO\n
                                      마케팅 주체: 없음, 마케팅 대상: 음악 좋아하시는 분들, 할인: 없음, 프로모션: 김태현 언택트 랜선콘서트"""},
    {"role": "user", "content": f"""{text}\n
                                    위 문장에서 마케팅 주체, 마케팅 대상, 할인, 프로모션 정보를 제외한 추가적인 마케팅 정보 3개 정도 더 알려줘"""}
]
result = generate_response(messages)
print(f"원본 : {text}")
print(result)

원본 : ★올리브영=세일 천재★\세일할 때마다 혜택은 UPGRADE⬆️\이번에도 필수 뷰티템만 천재적 세일 특.가.로 제공 중(~12/5)
1. 이벤트 기간: 12월 5일까지
2. 세일 품목: 필수 뷰티템
3. 혜택 등급: UPGRADE

마케팅 주체: 올리브영, 마케팅 대상: 뷰티 관련 상품 구매자, 할인: 천재적 세일 특가, 프로모션: 없음