# Install

In [ ]:
!pip3 install pshmodule

In [ ]:
!pip3 install pickle5

In [ ]:
!pip3 install pandas==1.5.0

In [ ]:
!pip3 install swifter

In [ ]:
!pip3 install openai

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Data Load

In [1]:
import sys
sys.path.append('/content/drive/MyDrive/Advertising_By_Personality/src/business_model')
print(sys.path)

['/content', '/env/python', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.10/dist-packages/IPython/extensions', '/root/.ipython', '/content/drive/MyDrive/Advertising_By_Personality/src/business_model']

In [2]:
import swifter
import config as cfg
import pandas as pd
from tqdm import tqdm
from pshmodule.utils import filemanager as fm

In [3]:
df = fm.load(cfg.origin_data)

extension : .xlsx
Loaded 25000 records from /content/drive/MyDrive/Advertising_By_Personality/data/origin/origin.xlsx

In [4]:
df.rename(columns={'관리번호':'no', '광고 구분':'advertisement_type', '마케팅전략':'marketing_strategy', '일상정보':'daily_information', '시즌정보':'season_information', '분류':'type', '제목':'title', '본문':'content', '납품차수':'degree'}, inplace=True)

In [5]:
df.head()

,no,advertisement_type,marketing_strategy,daily_information,season_information,type,title,content,degree
0,1,NaN,NaN,NaN,NaN,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰,"마지막 2일! [계절밥상 디너/주말 1만원, 런치 5천원 할인 쿠폰] 9월30일까지...",NaN
1,1,할인/쿠폰/혜택,"매력적인숫자(시간,돈)",NaN,NaN,ST,★최대 1만원★ 계절밥상 할인쿠폰,"이.틀.만! VIP 고객 디너&주말 1만원, 런치 5천원 할인 쿠폰 놓치지 마세요!",1차
2,1,할인/쿠폰/혜택,핵심정보만 전달,NaN,NaN,SF,ONLY VIP! 할인쿠폰♬,소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상] 디너/주말 1만원+런치 5천...,1차
3,1,할인/쿠폰/혜택,호기심유발(질문),NaN,NaN,NT,이 혜택💰 놓치지 않을 거예요,"[계절밥상] 디너/주말 1O,OOO원, 런치 5,OOO원 할인\\9월 30일까지🚨",1차
4,1,할인/쿠폰/혜택,호기심유발(이모지),NaN,NaN,NF,VIP님들만을 위한 쿠폰 도착💌,계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/주말 할인 쿠폰(~9/30) 사용하...,1차

# Preprocessing

In [6]:
from pshmodule.processing import processing as p

In [7]:
nlp = p.Nlp()

In [8]:
df_temp = df.copy()

In [9]:
# 이모지를 Java, JavaScript, JSON 유니코드 코드로 변경
df_temp['title_processing'] = df_temp.title.swifter.apply(nlp.convert_to_other_unicode)
df_temp['content_processing'] = df_temp.content.swifter.apply(nlp.convert_to_other_unicode)

Pandas Apply:   0%|          | 0/25000 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/25000 [00:00<?, ?it/s]

In [10]:
# \\\\ → \\
df_temp['title_processing'] = df_temp.title_processing.swifter.apply(lambda x: x.replace('\\\\', '\\'))
df_temp['content_processing'] = df_temp.content_processing.swifter.apply(lambda x: x.replace('\\\\', '\\'))

Pandas Apply:   0%|          | 0/25000 [00:00<?, ?it/s]

In [11]:
df_temp['content_processing'].iloc[2]

'소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상] 디너/주말 1만원+런치 5천원 할인 쿠폰 사용하기(~9/30)'

In [12]:
df_temp['input'] = df_temp.title_processing + '\\\\' + df_temp.content_processing
df_temp['content'] = df_temp.title + '\\\\' + df_temp.content

In [13]:
df_temp = df_temp[['no', 'season_information', 'type', 'input', 'content']]

In [14]:
df_temp.head()

,no,season_information,type,input,content
0,1,NaN,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...
1,1,NaN,ST,"★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런..."
2,1,NaN,SF,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\[계절밥상]...,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상...
3,1,NaN,NT,"이 혜택\ud83d\udcb0 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,O...","이 혜택💰 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,OOO원, 런치 5,O..."
4,1,NaN,NF,VIP님들만을 위한 쿠폰 도착\ud83d\udc8c\\계절밥상에서 든든한 한끼\ud...,VIP님들만을 위한 쿠폰 도착💌\\계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/...

random & 10 limit

In [15]:
df_temp = df_temp.sample(frac=1).reset_index(drop=True)

In [16]:
df_temp = df_temp.iloc[:10]

In [17]:
df_temp.head()

,no,season_information,type,input,content
0,3029,NaN,원문,"CJ ONE X 윙크\\4~7세맘 신청자 전원 책 4권 무료 + 1,000P","CJ ONE X 윙크\\4~7세맘 신청자 전원 책 4권 무료 + 1,000P"
1,1458,NaN,SF,"계절밥상 전어 반값 쿠폰!\\남다른 고소함과 부드러운 그 맛, 푸짐한 한상 차림 놓...","계절밥상 전어 반값 쿠폰!\\남다른 고소함과 부드러운 그 맛, 푸짐한 한상 차림 놓..."
2,664,NaN,NT,다 퍼주는 착한 친구\ud83d\ude07\\나야 나\ud83d\udc48 친구 맺...,"다 퍼주는 착한 친구😇\\나야 나👈 친구 맺으면 영화 예매권 줌💌\\퀴즈 풀면 1,..."
3,3730,NaN,ST,"쿠폰함에 [5천원 할인 쿠폰] 대기중\\더플레이스 5,OOO원 할인 쿠폰 사용하러 ...","쿠폰함에 [5천원 할인 쿠폰] 대기중\\더플레이스 5,OOO원 할인 쿠폰 사용하러 ..."
4,3811,NaN,NT,내일이면 1OO%가 O%로\ud83d\udce2\\오.늘.까.지⌛ [CJ ONE 최...,내일이면 1OO%가 O%로📢\\오.늘.까.지⌛ [CJ ONE 최애 브랜드] PICK...

# ChatGPT Test

In [18]:
import openai

In [19]:
# 발급받은 API 키 설정
OPENAI_API_KEY = "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"

# openai API 키 인증
openai.api_key = OPENAI_API_KEY
model = "gpt-4"

In [20]:
def generate_response(messages):
  response = openai.ChatCompletion.create(
      model=model,
      messages=messages
  )
  return response['choices'][0]['message']['content']

In [21]:
predict = []

for i in tqdm(df_temp.iterrows()):
  messages = [
      {"role": "system", "content": f"""너는 판매 촉진을 위한 마케팅 문구를 만드는 카피라이터야. 고객들이 반응하는 문구로 마케팅을 하려고 해.
                                        아래 예시처럼 다양한 영역의 마케팅 정보를 새롭게 추출하려고 해.\n
                                      '일요일에 데이트 어때~? [계절밥상] 소중한 사람과 함께 하는 통 돼지구이 FLEX! 만원 할인 쿠폰 받고 가요!'
                                        마케팅 주체: 계절밥상, 마케팅 대상: 일요일 데이트 고객, 혜택 조건: 없음, 할인 수치: 만원, 프로모션 품목: 통 돼지구이 할인 쿠폰, 이벤트 기간: 일요일, 시즌 정보: 없음\n
                                      '짝짝짝! 친구 맺으면 1,000P~ 정답만 맞히면 포인트 주는 이벤트! 퀴즈 맞히고 1,000P 바로 받아가기'
                                        마케팅 주체: 없음, 마케팅 대상: 일반 고객, 혜택 조건: 친구 맺기, 할인 수치: 없음, 프로모션 품목: 1,000 포인트, 이벤트 기간: 없음, 시즌 정보: 없음\n
                                      '이번 봄 나들이는 빕스로\u2753 제철 과일 딸기 가득 [딸기홀릭] 시즌♥ 시크릿박스 쿠폰 쓰고 딸기 디저트 저.렴.하.게 즐기자'
                                        마케팅 주체: 빕스, 마케팅 대상: 일반 고객, 혜택 조건: 없음, 할인 수치: 없음, 프로모션 품목: 시크릿박스 쿠폰, 이벤트 기간: 없음, 시즌 정보: 봄맞이\n
                                      '매주 Monday는 면세day♬\[신세계 면세점]에서 매주 월,화에 드리는 할인 혜택!\[TAG1]님, 일상에 일에 지치셨다면? 신나는 면세 쇼핑으로 치유하자Go~'
                                        마케팅 주체: 신세계 면세점, 마케팅 대상: 면세 대상 고객, 혜택 조건: 없음, 할인 수치: 없음, 프로모션 품목: 면세 쇼핑 품목, 이벤트 기간: 매주 월요일, 화요일, 시즌 정보: 없음\n
                                        '힙스터들의 성지, 성수동 갈 사람?\\ud83d\udd25화제의 팝업 전시, 뮤지엄오브컬러가 고객님을 기다려욧!\힙쟁이라면 안 간 사람 없다던데\ud83d\udc41️...단독 3O% 할인 중'
                                        마케팅 주체: 없음, 마케팅 대상: 힙스터들, 성수동 방문객, 혜택 조건: 없음, 할인 수치: 30% 할인, 프로모션 품목: 뮤지엄오브컬러, 이벤트 기간: 없음, 시즌 정보: 없음"""},
      {"role": "user", "content": f"""{i[1]['input']}\n
                                      위 문장에서 아래 정보를 뽑아줘.
                                      마케팅 주체: ,\n
                                      마케팅 대상: ,\n
                                      혜택 조건: ,\n
                                      할인 수치: ,\n
                                      프로모션 품목: ,\n
                                      이벤트 기간: ,\n
                                      시즌 정보: """}
  ]
  result = generate_response(messages)
  predict.append(result)

df_temp['predict'] = predict

10it [03:07, 18.73s/it]

In [22]:
df_temp.head()

,no,season_information,type,input,content,predict
0,3029,NaN,원문,"CJ ONE X 윙크\\4~7세맘 신청자 전원 책 4권 무료 + 1,000P","CJ ONE X 윙크\\4~7세맘 신청자 전원 책 4권 무료 + 1,000P","마케팅 주체: CJ ONE X 윙크,\n\n마케팅 대상: 4~7세 아이를 둔 엄마들..."
1,1458,NaN,SF,"계절밥상 전어 반값 쿠폰!\\남다른 고소함과 부드러운 그 맛, 푸짐한 한상 차림 놓...","계절밥상 전어 반값 쿠폰!\\남다른 고소함과 부드러운 그 맛, 푸짐한 한상 차림 놓...","마케팅 주체: 계절밥상,\n\n마케팅 대상: 일반 고객,\n\n혜택 조건: 없음,\..."
2,664,NaN,NT,다 퍼주는 착한 친구\ud83d\ude07\\나야 나\ud83d\udc48 친구 맺...,"다 퍼주는 착한 친구😇\\나야 나👈 친구 맺으면 영화 예매권 줌💌\\퀴즈 풀면 1,...","마케팅 주체: 없음,\n\n마케팅 대상: 일반 고객, 친구들,\n\n혜택 조건: 친..."
3,3730,NaN,ST,"쿠폰함에 [5천원 할인 쿠폰] 대기중\\더플레이스 5,OOO원 할인 쿠폰 사용하러 ...","쿠폰함에 [5천원 할인 쿠폰] 대기중\\더플레이스 5,OOO원 할인 쿠폰 사용하러 ...","마케팅 주체: 더플레이스,\n\n마케팅 대상: 쿠폰 사용 고객,\n\n혜택 조건: ..."
4,3811,NaN,NT,내일이면 1OO%가 O%로\ud83d\udce2\\오.늘.까.지⌛ [CJ ONE 최...,내일이면 1OO%가 O%로📢\\오.늘.까.지⌛ [CJ ONE 최애 브랜드] PICK...,"마케팅 주체: CJ ONE,\n\n마케팅 대상: 일반 고객,\n\n혜택 조건: CJ..."

In [23]:
df_temp['predict_temp'] = df_temp.predict.swifter.apply(lambda x: x.replace('마케팅 주체: ', '').replace('마케팅 대상: ', '').replace('혜택 조건: ', '').replace('할인 수치: ', '').replace('프로모션 품목: ', '').replace('이벤트 기간: ', '').replace('시즌 정보: ', ''))

Pandas Apply:   0%|          | 0/10 [00:00<?, ?it/s]

In [24]:
df_split = df_temp.predict_temp.str.split(',\n\n', expand=True)

In [25]:
df_split.head()

,0,1,2,3,4,5,6
0,CJ ONE X 윙크,4~7세 아이를 둔 엄마들(맘),신청자 전원,없음,"책 4권 무료 + 1,000 포인트",없음,없음
1,계절밥상,일반 고객,없음,50% 할인,전어 반값 쿠폰,없음,없음
2,없음,"일반 고객, 친구들","친구 맺기, 퀴즈 풀기",없음,"영화 예매권, 1,000포인트",없음,없음
3,더플레이스,쿠폰 사용 고객,없음,"5,000원",더플레이스 외식 (모든 메뉴),없음,없음
4,CJ ONE,일반 고객,CJ ONE 최애 브랜드 PICK,없음,100% 포인트,오늘까지,없음

In [26]:
df_result = pd.concat([df_temp, df_split], axis=1)

In [27]:
df_result.tail()

,no,season_information,type,input,content,predict,predict_temp,0,1,2,3,4,5,6
5,1804,NaN,원문,\u2764\ufe0fN서울타워 어반그린야드 메뉴 쿠폰 증정\u2764\ufe0f\...,\u2764\ufe0fN서울타워 어반그린야드 메뉴 쿠폰 증정\u2764\ufe0f\...,"마케팅 주체: N서울타워 어반그린야드,\n\n마케팅 대상: 전체 서울 관람객, 피크...","N서울타워 어반그린야드,\n\n전체 서울 관람객, 피크닉 분위기를 즐기고 싶은 고객...",N서울타워 어반그린야드,"전체 서울 관람객, 피크닉 분위기를 즐기고 싶은 고객",없음,없음,어반그린야드 메뉴 쿠폰,없음,한 여름
6,4030,NaN,ST,"원하는 케이크 고르려면?\u27a1️예약하기\\지금 투썸 홀케이크 예약하면 3,OO...","원하는 케이크 고르려면?➡️예약하기\\지금 투썸 홀케이크 예약하면 3,OOO원 할인...","마케팅 주체: 투썸플레이스,\n\n마케팅 대상: 케이크 구매 고객,\n\n혜택 조건...","투썸플레이스,\n\n케이크 구매 고객,\n\n홀케이크 예약 및 모바일 투썸 등록,\...",투썸플레이스,케이크 구매 고객,홀케이크 예약 및 모바일 투썸 등록,"3,000원",투썸 홀케이크,없음,없음
7,4291,NaN,NF,"주말이 오기 전, 날 찾아주시길\ud83d\ude4f\\CGV가 [TAG1]님께만 ...","주말이 오기 전, 날 찾아주시길🙏\\CGV가 [TAG1]님께만 넣어 드렸는데..👀 ...","마케팅 주체: CGV,\n\n마케팅 대상: [TAG1]님(고객),\n\n혜택 조건:...","CGV,\n\n[TAG1]님(고객),\n\n없음,\n\n없음, (1+1 제공)\n\...",CGV,[TAG1]님(고객),없음,"없음, (1+1 제공)\n\n영화쿠폰",없음,주말 이전,None
8,1359,NaN,NF,Hoxy.. 김치찌개만 삼일째..?\\안대안대!\ud83d\ude23 [TAG1]님...,Hoxy.. 김치찌개만 삼일째..?\\안대안대!😣 [TAG1]님의 집밥 퀄리티 보호...,"마케팅 주체: 쿡킷,\n\n마케팅 대상: [TAG1]님(일반 고객),\n\n혜택 조...","쿡킷,\n\n[TAG1]님(일반 고객),\n\n없음,\n\n30% 할인,\n\n쿡킷...",쿡킷,[TAG1]님(일반 고객),없음,30% 할인,쿡킷,없음,없음
9,3082,NaN,ST,[D-5] CJ TOWN 쿠폰 만료\\곧 소/멸/예/정 [CJ TOWN] 쿠폰 확인...,[D-5] CJ TOWN 쿠폰 만료\\곧 소/멸/예/정 [CJ TOWN] 쿠폰 확인...,"마케팅 주체: CJ TOWN,\n\n마케팅 대상: [TAG1]님,\n\n혜택 조건:...","CJ TOWN,\n\n[TAG1]님,\n\n없음,\n\n없음,\n\nCJ TOWN ...",CJ TOWN,[TAG1]님,없음,없음,CJ TOWN 쿠폰,D-5,없음

In [31]:
df_result.rename(columns={'no':'관리번호', 'advertisement_type':'광고 구분', 'marketing_strategy':'마케팅 전략', 'daily_information':'일상 정보', 'season_information':'시즌 정보_원본', 'type':'분류', 'title':'제목', 'content':'본문', 'degree':'납품차수', 'content':'원본', 0:'마케팅 주체', 1:'마케팅 대상',	2:'혜택 조건', 3:'할인 수치', 4:'프로모션 품목', 5:'이벤트 기간', 6:'시즌 정보', 'input':'입력 데이터'}, inplace=True)

In [33]:
df_result = df_result[['관리번호', '시즌 정보_원본', '분류', '원본', '마케팅 주체', '마케팅 대상', '혜택 조건', '할인 수치', '프로모션 품목', '이벤트 기간', '시즌 정보', '입력 데이터']]

In [34]:
df_result.head()

,관리번호,시즌 정보_원본,분류,원본,마케팅 주체,마케팅 대상,혜택 조건,할인 수치,프로모션 품목,이벤트 기간,시즌 정보,입력 데이터
0,3029,NaN,원문,"CJ ONE X 윙크\\4~7세맘 신청자 전원 책 4권 무료 + 1,000P",CJ ONE X 윙크,4~7세 아이를 둔 엄마들(맘),신청자 전원,없음,"책 4권 무료 + 1,000 포인트",없음,없음,"CJ ONE X 윙크\\4~7세맘 신청자 전원 책 4권 무료 + 1,000P"
1,1458,NaN,SF,"계절밥상 전어 반값 쿠폰!\\남다른 고소함과 부드러운 그 맛, 푸짐한 한상 차림 놓...",계절밥상,일반 고객,없음,50% 할인,전어 반값 쿠폰,없음,없음,"계절밥상 전어 반값 쿠폰!\\남다른 고소함과 부드러운 그 맛, 푸짐한 한상 차림 놓..."
2,664,NaN,NT,"다 퍼주는 착한 친구😇\\나야 나👈 친구 맺으면 영화 예매권 줌💌\\퀴즈 풀면 1,...",없음,"일반 고객, 친구들","친구 맺기, 퀴즈 풀기",없음,"영화 예매권, 1,000포인트",없음,없음,다 퍼주는 착한 친구\ud83d\ude07\\나야 나\ud83d\udc48 친구 맺...
3,3730,NaN,ST,"쿠폰함에 [5천원 할인 쿠폰] 대기중\\더플레이스 5,OOO원 할인 쿠폰 사용하러 ...",더플레이스,쿠폰 사용 고객,없음,"5,000원",더플레이스 외식 (모든 메뉴),없음,없음,"쿠폰함에 [5천원 할인 쿠폰] 대기중\\더플레이스 5,OOO원 할인 쿠폰 사용하러 ..."
4,3811,NaN,NT,내일이면 1OO%가 O%로📢\\오.늘.까.지⌛ [CJ ONE 최애 브랜드] PICK...,CJ ONE,일반 고객,CJ ONE 최애 브랜드 PICK,없음,100% 포인트,오늘까지,없음,내일이면 1OO%가 O%로\ud83d\udce2\\오.늘.까.지⌛ [CJ ONE 최...

File Save

In [37]:
fm.save('/content/drive/MyDrive/Advertising_By_Personality/data/reports/predict.xlsx', df_result)

Saved 10 records

##### 마케팅 정보 찾기

In [ ]:
text = "★올리브영=세일 천재★\\세일할 때마다 혜택은 UPGRADE⬆️\\이번에도 필수 뷰티템만 천재적 세일 특.가.로 제공 중(~12/5)"

In [ ]:
messages = [
    {"role": "system", "content": f"""'일요일에 데이트 어때~? [계절밥상] 소중한 사람과 함께 하는 통 돼지구이 FLEX! 만원 할인 쿠폰 받고 가요!'\n
                                      마케팅 주체: 계절밥상, 마케팅 대상: 주말 데이트, 할인: 만원 할인, 프로모션: 없음
                                      '짝짝짝! 친구 맺으면 1,000P~ 정답만 맞히면 포인트 주는 이벤트! 퀴즈 맞히고 1,000P 바로 받아가기'\n
                                      마케팅 주체: 없음, 마케팅 대상: 친구 맺기, 퀴즈 정답 맞히기, 할인: 없음, 프로모션: 1,000 포인트 제공
                                      음악 좋아하시는 분들 이거 다 알던데\\\\천재적인 드러머 [김태현 언택트 랜선콘서트] 지금 라방으로 진행 중★\\재즈&국악의 환상적 콜라보 만나보러 GO\n
                                      마케팅 주체: 없음, 마케팅 대상: 음악 좋아하시는 분들, 할인: 없음, 프로모션: 김태현 언택트 랜선콘서트"""},
    {"role": "user", "content": f"""{text}\n
                                    위 문장에서 마케팅 주체, 마케팅 대상, 할인, 프로모션 정보를 제외한 추가적인 마케팅 정보 3개 정도 더 알려줘"""}
]
result = generate_response(messages)
print(f"원본 : {text}")
print(result)

원본 : ★올리브영=세일 천재★\세일할 때마다 혜택은 UPGRADE⬆️\이번에도 필수 뷰티템만 천재적 세일 특.가.로 제공 중(~12/5)
1. 이벤트 기간: 12월 5일까지
2. 세일 품목: 필수 뷰티템
3. 혜택 등급: UPGRADE

마케팅 주체: 올리브영, 마케팅 대상: 뷰티 관련 상품 구매자, 할인: 천재적 세일 특가, 프로모션: 없음