# Install

In [ ]:
!pip3 install pshmodule

In [ ]:
!pip3 install pickle5

In [ ]:
!pip3 install pandas==1.5.0

In [ ]:
!pip3 install swifter

In [ ]:
!pip3 install openai

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Data Load

In [7]:
import sys
sys.path.append('/content/drive/MyDrive/Advertising_By_Personality/src/business_model/keyword_extraction')
print(sys.path)

['/content', '/env/python', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.10/dist-packages/IPython/extensions', '/root/.ipython', '/content/drive/MyDrive/Advertising_By_Personality/src/business_model/keyword_extraction']

In [8]:
import swifter
import config as cfg
import pandas as pd
from tqdm import tqdm
from pshmodule.utils import filemanager as fm

In [ ]:
df = fm.load(cfg.origin_data)

extension : .xlsx
Loaded 25000 records from /content/drive/MyDrive/Advertising_By_Personality/data/origin/origin.xlsx

In [ ]:
df.rename(columns={'관리번호':'no', '광고 구분':'advertisement_type', '마케팅전략':'marketing_strategy', '일상정보':'daily_information', '시즌정보':'season_information', '분류':'type', '제목':'title', '본문':'content', '납품차수':'degree'}, inplace=True)

In [ ]:
df.head()

,no,advertisement_type,marketing_strategy,daily_information,season_information,type,title,content,degree
0,1,NaN,NaN,NaN,NaN,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰,"마지막 2일! [계절밥상 디너/주말 1만원, 런치 5천원 할인 쿠폰] 9월30일까지...",NaN
1,1,할인/쿠폰/혜택,"매력적인숫자(시간,돈)",NaN,NaN,ST,★최대 1만원★ 계절밥상 할인쿠폰,"이.틀.만! VIP 고객 디너&주말 1만원, 런치 5천원 할인 쿠폰 놓치지 마세요!",1차
2,1,할인/쿠폰/혜택,핵심정보만 전달,NaN,NaN,SF,ONLY VIP! 할인쿠폰♬,소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상] 디너/주말 1만원+런치 5천...,1차
3,1,할인/쿠폰/혜택,호기심유발(질문),NaN,NaN,NT,이 혜택💰 놓치지 않을 거예요,"[계절밥상] 디너/주말 1O,OOO원, 런치 5,OOO원 할인\\9월 30일까지🚨",1차
4,1,할인/쿠폰/혜택,호기심유발(이모지),NaN,NaN,NF,VIP님들만을 위한 쿠폰 도착💌,계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/주말 할인 쿠폰(~9/30) 사용하...,1차

# Preprocessing

In [ ]:
from pshmodule.processing import processing as p

In [ ]:
nlp = p.Nlp()

In [ ]:
df_temp = df.copy()

In [ ]:
# 이모지를 Java, JavaScript, JSON 유니코드 코드로 변경
df_temp['title_processing'] = df_temp.title.swifter.apply(nlp.convert_to_other_unicode)
df_temp['content_processing'] = df_temp.content.swifter.apply(nlp.convert_to_other_unicode)

Pandas Apply:   0%|          | 0/25000 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/25000 [00:00<?, ?it/s]

In [ ]:
# \\\\ → \\
df_temp['title_processing'] = df_temp.title_processing.swifter.apply(lambda x: x.replace('\\\\', '\\'))
df_temp['content_processing'] = df_temp.content_processing.swifter.apply(lambda x: x.replace('\\\\', '\\'))

# \n\n -> \\\\
df_temp['title_processing'] = df_temp.title_processing.replace('\n\n', '\\\\').replace('\n', '\\')
df_temp['content_processing'] = df_temp.content_processing.replace('\n\n', '\\\\').replace('\n', '\\')

Pandas Apply:   0%|          | 0/25000 [00:00<?, ?it/s]

In [ ]:
df_temp['content_processing'].iloc[2]

'소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상] 디너/주말 1만원+런치 5천원 할인 쿠폰 사용하기(~9/30)'

In [ ]:
df_temp['input'] = df_temp.title_processing + '\\\\' + df_temp.content_processing
df_temp['content'] = df_temp.title + '\\\\' + df_temp.content

In [ ]:
df_temp = df_temp[['no', 'season_information', 'type', 'input', 'content']]

In [ ]:
df_temp.head()

,no,season_information,type,input,content
0,1,NaN,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...
1,1,NaN,ST,"★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런..."
2,1,NaN,SF,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\[계절밥상]...,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상...
3,1,NaN,NT,"이 혜택\ud83d\udcb0 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,O...","이 혜택💰 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,OOO원, 런치 5,O..."
4,1,NaN,NF,VIP님들만을 위한 쿠폰 도착\ud83d\udc8c\\계절밥상에서 든든한 한끼\ud...,VIP님들만을 위한 쿠폰 도착💌\\계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/...

In [ ]:
df_temp.shape

(25000, 5)

##### 100 test

In [ ]:
df_temp = df_temp.iloc[:100]

In [ ]:
df_temp.shape

(100, 5)

##### random & 10 limit

In [ ]:
df_temp = df_temp.sample(frac=1).reset_index(drop=True)

In [ ]:
df_temp = df_temp.iloc[:10]

In [ ]:
df_temp.head()

,no,season_information,type,input,content
0,4360,NaN,원문,"오늘처럼 추운 날엔, 투썸 커피 한잔!\\[TAG1]님, 지금 쿠폰함에서 [투썸 아...","오늘처럼 추운 날엔, 투썸 커피 한잔!\\[TAG1]님, 지금 쿠폰함에서 [투썸 아..."
1,430,NaN,SF,밥 먹고 졸릴 땐? 룰렛 돌리기!\\[커피교환권] OR [포인트] 1OO% 당첨!\...,밥 먹고 졸릴 땐? 룰렛 돌리기!\\[커피교환권] OR [포인트] 1OO% 당첨!\...
2,955,NaN,NF,항상 잘 챙겨드셨으면 해서\\고객님을 위해 준비했어요\ud83d\udc96\[쿡킷 ...,항상 잘 챙겨드셨으면 해서\\고객님을 위해 준비했어요💖\\[쿡킷 5O% 할인쿠폰] ...
3,1386,NaN,NT,투썸에 올 수밖에 없을걸요?\u2763️\\왜냐하면 [투썸X모나미 데일리키트 할인쿠...,투썸에 올 수밖에 없을걸요?❣️\\왜냐하면 [투썸X모나미 데일리키트 할인쿠폰]💌을 ...
4,1466,NaN,ST,종/료/임/박! 뮤지컬 할인\\뮤지컬 [신비아파트] 최대 6O% 할인 오.늘.까.지...,종/료/임/박! 뮤지컬 할인\\뮤지컬 [신비아파트] 최대 6O% 할인 오.늘.까.지...

# ChatGPT Test

In [ ]:
import openai

In [ ]:
# 발급받은 API 키 설정
OPENAI_API_KEY = "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"

# openai API 키 인증
openai.api_key = OPENAI_API_KEY
model = "gpt-4"

In [ ]:
def generate_response(messages):
  response = openai.ChatCompletion.create(
      model=model,
      messages=messages
  )
  return response['choices'][0]['message']['content']

In [ ]:
predict = []

for i in tqdm(df_temp.iterrows()):
  messages = [
      {"role": "system", "content": f"""너는 판매 촉진을 위한 마케팅 문구를 만드는 카피라이터야. 고객들이 반응하는 문구로 마케팅을 하려고 해.
                                        아래 예시처럼 다양한 영역의 마케팅 정보를 새롭게 추출하려고 해.\n
                                      '일요일에 데이트 어때~? [계절밥상] 소중한 사람과 함께 하는 통 돼지구이 FLEX! 만원 할인 쿠폰 받고 가요!'
                                        마케팅 주체: 계절밥상, 마케팅 대상: 일요일 데이트 고객, 혜택 조건: 없음, 할인 수치: 만원, 프로모션 품목: 통 돼지구이 할인 쿠폰, 이벤트 기간: 일요일, 시즌 정보: 없음\n
                                      '짝짝짝! 친구 맺으면 1,000P~ 정답만 맞히면 포인트 주는 이벤트! 퀴즈 맞히고 1,000P 바로 받아가기'
                                        마케팅 주체: 없음, 마케팅 대상: 일반 고객, 혜택 조건: 친구 맺기, 할인 수치: 없음, 프로모션 품목: 1,000 포인트, 이벤트 기간: 없음, 시즌 정보: 없음\n
                                      '이번 봄 나들이는 빕스로\u2753 제철 과일 딸기 가득 [딸기홀릭] 시즌♥ 시크릿박스 쿠폰 쓰고 딸기 디저트 저.렴.하.게 즐기자'
                                        마케팅 주체: 빕스, 마케팅 대상: 일반 고객, 혜택 조건: 없음, 할인 수치: 없음, 프로모션 품목: 시크릿박스 쿠폰, 이벤트 기간: 없음, 시즌 정보: 봄맞이\n
                                      '매주 Monday는 면세day♬\[신세계 면세점]에서 매주 월,화에 드리는 할인 혜택!\[TAG1]님, 일상에 일에 지치셨다면? 신나는 면세 쇼핑으로 치유하자Go~'
                                        마케팅 주체: 신세계 면세점, 마케팅 대상: 면세 대상 고객, 혜택 조건: 없음, 할인 수치: 없음, 프로모션 품목: 면세 쇼핑 품목, 이벤트 기간: 매주 월요일, 화요일, 시즌 정보: 없음\n
                                        '힙스터들의 성지, 성수동 갈 사람?\\ud83d\udd25화제의 팝업 전시, 뮤지엄오브컬러가 고객님을 기다려욧!\힙쟁이라면 안 간 사람 없다던데\ud83d\udc41️...단독 3O% 할인 중'
                                        마케팅 주체: 없음, 마케팅 대상: 힙스터들, 성수동 방문객, 혜택 조건: 없음, 할인 수치: 30% 할인, 프로모션 품목: 뮤지엄오브컬러, 이벤트 기간: 없음, 시즌 정보: 없음"""},
      {"role": "user", "content": f"""{i[1]['input']}\n
                                      위 문장에서 아래 정보를 뽑아줘.
                                      마케팅 주체: ,\n
                                      마케팅 대상: ,\n
                                      혜택 조건: ,\n
                                      할인 수치: ,\n
                                      프로모션 품목: ,\n
                                      이벤트 기간: ,\n
                                      시즌 정보: """}
  ]
  result = generate_response(messages)
  print(f"원문 : {i[1]['input']}")
  print(f"답변 : {result}")
  print("-"*100)
  predict.append(result)

In [ ]:
df_temp = df_temp.iloc[:77]

In [ ]:
df_temp['predict'] = predict

In [ ]:
df_temp.head()

,no,type,input,content,predict,predict_temp
0,1,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,"마케팅 주체: CJONE, 계절밥상,\n\n마케팅 대상: CJONE VIP 고객들,...","CJONE, 계절밥상,\n\nCJONE VIP 고객들,\n\n없음,\n\n1만원(디..."
1,1,ST,"★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객,\n\n혜택 조건: 디너 ...","계절밥상,\n\nVIP 고객,\n\n디너 & 주말 이용,\n\n최대 1만원 (디너 ..."
2,1,SF,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\[계절밥상]...,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상...,"마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객들,\n\n혜택 조건: 디너...","계절밥상,\n\nVIP 고객들,\n\n디너/주말/런치 사용 가능,\n\n디너/주말 ..."
3,1,NT,"이 혜택\ud83d\udcb0 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,O...","이 혜택💰 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,OOO원, 런치 5,O...",마케팅 주체: 계절밥상\n\n마케팅 대상: 일반 고객\n\n혜택 조건: 없음\n\n...,"계절밥상\n\n일반 고객\n\n없음\n\n디너/주말 10,000원, 런치 5,000..."
4,1,NF,VIP님들만을 위한 쿠폰 도착\ud83d\udc8c\\계절밥상에서 든든한 한끼\ud...,VIP님들만을 위한 쿠폰 도착💌\\계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/...,"마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객들,\n\n혜택 조건: 없음...","계절밥상,\n\nVIP 고객들,\n\n없음,\n\n없음 (하지만 런치/디너/주말 할..."

In [ ]:
df_temp['predict_temp'] = df_temp.predict.swifter.apply(lambda x: x.replace('마케팅 주체: ', '').replace('마케팅 대상: ', '').replace('혜택 조건: ', '').replace('할인 수치: ', '').replace('프로모션 품목: ', '').replace('이벤트 기간: ', '').replace('시즌 정보: ', ''))

Pandas Apply:   0%|          | 0/77 [00:00<?, ?it/s]

In [ ]:
df_temp.head()

,no,type,input,content,predict,predict_temp
0,1,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,"마케팅 주체: CJONE, 계절밥상,\n\n마케팅 대상: CJONE VIP 고객들,...","CJONE, 계절밥상,\n\nCJONE VIP 고객들,\n\n없음,\n\n1만원(디..."
1,1,ST,"★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객,\n\n혜택 조건: 디너 ...","계절밥상,\n\nVIP 고객,\n\n디너 & 주말 이용,\n\n최대 1만원 (디너 ..."
2,1,SF,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\[계절밥상]...,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상...,"마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객들,\n\n혜택 조건: 디너...","계절밥상,\n\nVIP 고객들,\n\n디너/주말/런치 사용 가능,\n\n디너/주말 ..."
3,1,NT,"이 혜택\ud83d\udcb0 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,O...","이 혜택💰 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,OOO원, 런치 5,O...",마케팅 주체: 계절밥상\n\n마케팅 대상: 일반 고객\n\n혜택 조건: 없음\n\n...,"계절밥상\n\n일반 고객\n\n없음\n\n디너/주말 10,000원, 런치 5,000..."
4,1,NF,VIP님들만을 위한 쿠폰 도착\ud83d\udc8c\\계절밥상에서 든든한 한끼\ud...,VIP님들만을 위한 쿠폰 도착💌\\계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/...,"마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객들,\n\n혜택 조건: 없음...","계절밥상,\n\nVIP 고객들,\n\n없음,\n\n없음 (하지만 런치/디너/주말 할..."

In [ ]:
df_split = df_temp.predict_temp.str.split(',\n\n', expand=True)

In [ ]:
df_split_true = df_split[df_split[0].str.contains('\n\n')]
df_split_true = df_split_true[0].str.split('\n\n', expand=True)

In [ ]:
df_split_false = df_split[~df_split[0].str.contains('\n\n')]

In [ ]:
print(df_split_false.shape)
print(df_split_true.shape)

(72, 7)
(5, 7)

In [ ]:
df_split_temp = pd.concat([df_split_false, df_split_true])

In [ ]:
# '마케팅 주체', '마케팅 대상', '혜택 조건', '할인 수치', '프로모션 품목', '이벤트 기간', '시즌 정보'
df_split_temp.rename(columns={0:'marketing_entity', 1:'marketing_target',	2:'benefit_conditions', 3:'discount_figure', 4:'promotional_items', 5:'event_period', 6:'season_information'}, inplace=True)

In [ ]:
df_split_temp.iloc[61:]

,marketing_entity,marketing_target,benefit_conditions,discount_figure,promotional_items,event_period,season_information
66,없음,일반 고객,메시지 카드 보내기,없음,페이백 선물,없음,없음
67,없음,소중한 사람에게 선물하는 고객,메시지카드+선물 보내기,없음,페이백 선물,없음,없음
68,없음,일반 고객,메시지카드로 마음을 전할 경우,없음,페이백 선물🎁,없음,없음
69,없음,소중한 사람에게 메시지 카드를 보내는 고객,메시지 카드 전송,없음,페이백 선물,없음,새해
70,없음,일반 고객,주사위 던지기,없음(100% 포인트 당첨 혜택),발뮤다 공기청정기,없음,없음
71,발뮤다,일반 고객,주사위 게임 참여,없음(포인트 증정),공기청정기,없음,미세먼지 시즌
72,발뮤다,일반 고객,주사위 이벤트 참여,없음,공기청정기,없음,없음
73,발뮤다,일반 고객,주사위 던지기,없음,공기청정기,없음,없음
74,없음,일반 고객,주사위 굴리기,없음,발뮤다 공기청정기,없음,없음
75,AIA,암보험 고객,암보험 상담,없음,1만원 혜택,없음,없음
76,AIA,암보험 보장 금액에 불만족한 고객,암보험 상담 받기,없음,1만원 혜택,없음,없음
3,계절밥상,일반 고객,없음,"디너/주말 10,000원, 런치 5,000원 할인","디너/주말, 런치 할인",9월 30일까지,없음
24,대림미술관,[TAG1] 회원,없음,없음,FREE PASS,오늘까지,없음
31,"CJ제일제당, CJ온마트",일반 고객,CJ온마트 프라임 회원,"30% 할인, 추가 40% 할인 쿠폰","베스트셀러 패키지, 프라임 회원권",16일까지,없음
32,"CJ제일제당, CJ온마트","SNS 리뷰 고객, 프라임 회원",없음,"30% 할인 (CJ제일제당 베스트셀러 패키지), 40% 할인 쿠폰 (CJ온마트 추가...","CJ제일제당 베스트셀러 패키지, CJ온마트 프라임 회원권",7월 16일까지,없음
59,"없음,","고객님,","포인트 사용,","최대 50%,","포인트 페이백,","단 이틀간,",없음

In [ ]:
# del df_temp['season_information']
df_result = pd.concat([df_split_temp, df_temp], axis=1)

In [ ]:
df_result = df_result.sort_index(ascending=True)

In [ ]:
df_result['marketing_entity'] = df_result.marketing_entity.apply(nlp.emoji_remove)
df_result['marketing_target'] = df_result.marketing_target.apply(nlp.emoji_remove)
df_result['benefit_conditions'] = df_result.benefit_conditions.apply(nlp.emoji_remove)
df_result['discount_figure'] = df_result.discount_figure.apply(nlp.emoji_remove)
df_result['promotional_items'] = df_result.promotional_items.apply(nlp.emoji_remove)
df_result['event_period'] = df_result.event_period.apply(nlp.emoji_remove)
df_result['season_information'] = df_result.season_information.apply(nlp.emoji_remove)

In [ ]:
df_result.fillna('없음', inplace=True)

In [ ]:
df_result.head()

,marketing_entity,marketing_target,benefit_conditions,discount_figure,promotional_items,event_period,season_information,no,type,input,content,predict,predict_temp
0,"CJONE, 계절밥상",CJONE VIP 고객들,없음,"1만원(디너/주말), 5천원(런치)","계절밥상 디너/주말, 런치 할인 쿠폰",9월 30일까지,없음.,1,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,"마케팅 주체: CJONE, 계절밥상,\n\n마케팅 대상: CJONE VIP 고객들,...","CJONE, 계절밥상,\n\nCJONE VIP 고객들,\n\n없음,\n\n1만원(디..."
1,계절밥상,VIP 고객,디너 & 주말 이용,"최대 1만원 (디너 & 주말: 1만원, 런치: 5천원)",할인 쿠폰,이틀,없음,1,ST,"★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객,\n\n혜택 조건: 디너 ...","계절밥상,\n\nVIP 고객,\n\n디너 & 주말 이용,\n\n최대 1만원 (디너 ..."
2,계절밥상,VIP 고객들,디너/주말/런치 사용 가능,"디너/주말 1만원, 런치 5천원 할인",할인 쿠폰,~9/30,없음,1,SF,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\[계절밥상]...,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상...,"마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객들,\n\n혜택 조건: 디너...","계절밥상,\n\nVIP 고객들,\n\n디너/주말/런치 사용 가능,\n\n디너/주말 ..."
3,계절밥상,일반 고객,없음,"디너/주말 10,000원, 런치 5,000원 할인","디너/주말, 런치 할인",9월 30일까지,없음,1,NT,"이 혜택\ud83d\udcb0 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,O...","이 혜택💰 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,OOO원, 런치 5,O...",마케팅 주체: 계절밥상\n\n마케팅 대상: 일반 고객\n\n혜택 조건: 없음\n\n...,"계절밥상\n\n일반 고객\n\n없음\n\n디너/주말 10,000원, 런치 5,000..."
4,계절밥상,VIP 고객들,없음,없음 (하지만 런치/디너/주말 할인 쿠폰이 존재함),"쿠폰 사용을 통한 런치, 디너, 주말 할인",9/30까지,없음,1,NF,VIP님들만을 위한 쿠폰 도착\ud83d\udc8c\\계절밥상에서 든든한 한끼\ud...,VIP님들만을 위한 쿠폰 도착💌\\계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/...,"마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객들,\n\n혜택 조건: 없음...","계절밥상,\n\nVIP 고객들,\n\n없음,\n\n없음 (하지만 런치/디너/주말 할..."

In [ ]:
df_result.rename(columns={'input':'label'}, inplace=True)

In [ ]:
df_result.head()

,marketing_entity,marketing_target,benefit_conditions,discount_figure,promotional_items,event_period,season_information,no,type,label,content,predict,predict_temp
0,"CJONE, 계절밥상",CJONE VIP 고객들,없음,"1만원(디너/주말), 5천원(런치)","계절밥상 디너/주말, 런치 할인 쿠폰",9월 30일까지,없음.,1,원문,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,[CJONE VIP] 계절밥상 1만원/5천원 할인쿠폰\\마지막 2일! [계절밥상 디...,"마케팅 주체: CJONE, 계절밥상,\n\n마케팅 대상: CJONE VIP 고객들,...","CJONE, 계절밥상,\n\nCJONE VIP 고객들,\n\n없음,\n\n1만원(디..."
1,계절밥상,VIP 고객,디너 & 주말 이용,"최대 1만원 (디너 & 주말: 1만원, 런치: 5천원)",할인 쿠폰,이틀,없음,1,ST,"★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","★최대 1만원★ 계절밥상 할인쿠폰\\이.틀.만! VIP 고객 디너&주말 1만원, 런...","마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객,\n\n혜택 조건: 디너 ...","계절밥상,\n\nVIP 고객,\n\n디너 & 주말 이용,\n\n최대 1만원 (디너 ..."
2,계절밥상,VIP 고객들,디너/주말/런치 사용 가능,"디너/주말 1만원, 런치 5천원 할인",할인 쿠폰,~9/30,없음,1,SF,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\[계절밥상]...,ONLY VIP! 할인쿠폰♬\\소중한 이들과 더 든든하게 먹고 싶다면?\\[계절밥상...,"마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객들,\n\n혜택 조건: 디너...","계절밥상,\n\nVIP 고객들,\n\n디너/주말/런치 사용 가능,\n\n디너/주말 ..."
3,계절밥상,일반 고객,없음,"디너/주말 10,000원, 런치 5,000원 할인","디너/주말, 런치 할인",9월 30일까지,없음,1,NT,"이 혜택\ud83d\udcb0 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,O...","이 혜택💰 놓치지 않을 거예요\\[계절밥상] 디너/주말 1O,OOO원, 런치 5,O...",마케팅 주체: 계절밥상\n\n마케팅 대상: 일반 고객\n\n혜택 조건: 없음\n\n...,"계절밥상\n\n일반 고객\n\n없음\n\n디너/주말 10,000원, 런치 5,000..."
4,계절밥상,VIP 고객들,없음,없음 (하지만 런치/디너/주말 할인 쿠폰이 존재함),"쿠폰 사용을 통한 런치, 디너, 주말 할인",9/30까지,없음,1,NF,VIP님들만을 위한 쿠폰 도착\ud83d\udc8c\\계절밥상에서 든든한 한끼\ud...,VIP님들만을 위한 쿠폰 도착💌\\계절밥상에서 든든한 한끼🍱 어때요?\\런치/디너/...,"마케팅 주체: 계절밥상,\n\n마케팅 대상: VIP 고객들,\n\n혜택 조건: 없음...","계절밥상,\n\nVIP 고객들,\n\n없음,\n\n없음 (하지만 런치/디너/주말 할..."

##### For Report

In [ ]:
# df_result.rename(columns={'no':'관리번호', 'advertisement_type':'광고 구분', 'marketing_strategy':'마케팅 전략', 'daily_information':'일상 정보', 'season_information':'시즌 정보_원본', 'type':'분류', 'title':'제목', 'content':'본문', 'degree':'납품차수', 'content':'원본', 0:'마케팅 주체', 1:'마케팅 대상',	2:'혜택 조건', 3:'할인 수치', 4:'프로모션 품목', 5:'이벤트 기간', 6:'시즌 정보', 'input':'입력 데이터'}, inplace=True)

In [ ]:
# df_result = df_result[['관리번호', '시즌 정보_원본', '분류', '원본', '마케팅 주체', '마케팅 대상', '혜택 조건', '할인 수치', '프로모션 품목', '이벤트 기간', '시즌 정보', '입력 데이터']]

##### File Save

In [20]:
import json

In [21]:
path = '/content/drive/MyDrive/Advertising_By_Personality/data/train_ployglot.json'

In [ ]:
temp_dict = [{"marketing_entity": row['marketing_entity'].strip(), "marketing_target": row['marketing_target'].strip(), "benefit_conditions": row['benefit_conditions'].strip(), "discount_figure": row['discount_figure'].strip(), "promotional_items": row['promotional_items'].strip(), "event_period": row['event_period'].strip(), "season_information": row['season_information'].strip(), "label": row['label'].strip()} for _, row in df_result.iterrows()]

In [ ]:
temp_dict[:5]

In [ ]:
with open(path, 'w', encoding='utf-8') as f:
  for line in temp_dict:
    json_record = json.dumps(line, ensure_ascii=False)
    f.write(json_record + '\n')

##### File Load

In [24]:
import json

In [25]:
path = '/content/drive/MyDrive/Advertising_By_Personality/data/train_polyglot.json'
data = []

In [26]:
with open(path, 'r', encoding='utf-8') as f:
    for line in f:
        data.append(json.loads(line.rstrip('\n|\r')))
data = pd.DataFrame(data)

이모지 제거

In [27]:
from pshmodule.processing import processing as p

In [28]:
nlp = p.Nlp()

In [29]:
data['marketing_entity'] = data.marketing_entity.apply(nlp.emoji_remove)
data['marketing_target'] = data.marketing_target.apply(nlp.emoji_remove)
data['benefit_conditions'] = data.benefit_conditions.apply(nlp.emoji_remove)
data['discount_figure'] = data.discount_figure.apply(nlp.emoji_remove)
data['promotional_items'] = data.promotional_items.apply(nlp.emoji_remove)
data['event_period'] = data.event_period.apply(nlp.emoji_remove)
data['season_information'] = data.season_information.apply(nlp.emoji_remove)

In [30]:
data.iloc[41:]

,marketing_entity,marketing_target,benefit_conditions,discount_figure,promotional_items,event_period,season_information,label
41,올리브영,일반 고객,득템프 1번 더 찍기,"5,000원",바캉스템 세일,올리브영데이,바캉스 시즌,"올리브영 바캉스템 초.특.가 세일\\득템프 1번만 더 찍으면 5,OOO원 할인쿠폰 ..."
42,올리브영,바캉스 감성을 좋아하는 고객,더득템프 1번 찍기,"5,000원 할인",바캉스위크 HOT아이템 특가 할인,없음,없음,#쇼핑하면서 #바캉스 감성 충전\\[올리브영데이] 바캉스위크 HOT아이템 특가 할인...
43,올영,일반 고객,득템프 1회 더 찍으면,"5,000원",바캉스 위크 특가 상품,없음,없음,"올영 바캉스 위크 특가⚡누리세오!\\아참, 득템프 1회 더 찍으면 5,OOO원 할인..."
44,올리브영,올영러버들,"두 가지 선물 ( 득템프 찍기, SNS 대란템)",없음(특가 가격으로 제공),올리브영 제품들 (바캉스 재질 관련),없음,없음,바캉스 재질 가득한 올리브영 데이\ud83c\udfc4\\올영러버들을 위한 선물 두...
45,더플레이스 화덕피자,"선착순 2,000명 고객","선착순 2,000명",무료,피자 쿠폰,매일,없음,"매일 선착순 2,000명에게 피자의 행운이\\더플레이스 화덕피자 70만개 판매 돌파..."
46,더플레이스,선착순 이벤트에 참여하는 고객들,"2,000명 안에 들기",100% (무료),화덕 피자,기간 정보 없음,없음,"2,OOO명 안에 들면 피자 무료!\\70만개 돌파 기념 [더플레이스] 화덕 피자 ..."
47,더플레이스,"먹스타그램에 관심 있는 고객, 피자 애호가","선착순 2,000명",무료,화덕피자,매일,없음,먹스타그램에서 핫-한 화덕피자♥\\[더플레이스] 화덕피자 70만개 판매 돌파 기념!...
48,더플레이스,일반 고객,선착순 2천 명,무료,화덕피자 쿠폰,"없음 (단, 매일 진행)",없음,피자 무료 쿠폰 드린다\ud83c\udf55\\당신도 될 수 있다 무료 쿠폰 당첨자...
49,더플레이스,일반 고객,선착순 2천 명,없음,화덕피자,매일,없음,고객님~ 화덕피자 좋아하세요?\ud83c\udf55\\[더플레이스]가 매일 선착순 ...
50,없음,일반 고객,보너스 퀴즈 풀기,없음,기프트카드 1천 포인트,없음,없음,기프트카드 득템 찬스!\\보너스 퀴즈 풀고 1천P까지 받으세요!
51,없음,일반 고객,보너스 퀴즈 풀기,없음,"1,000 포인트 기프트카드",없음,없음,퀴즈 풀고 ★1천P★ 받으러 GO\\지금 보너스 퀴즈만 풀면 기프트카드 득템 찬스가...
52,없음,소중한 고객님,퀴즈 정답 맞히기,없음,1천 포인트,없음,없음,기프트카드 득템 찬스 도착♬\\(쉿!) 소중한 고객님께만 드리는 정보♡\퀴즈 맞히기...
53,없음,일반 고객,퀴즈 풀기,없음,"1,000포인트 적립",없음,없음,깁카 득템하는 법 알려DREAM~\\보너스 퀴즈 풀면 끝! 이게 다라고? 퀴즈 풀고...
54,없음,퀴즈왕 찐천재 및 일반 고객,"정답자, 보너스 퀴즈 응모자에게 포인트 혜택",없음,"기프트 카드, 포인트",없음,없음,똑똑한 퀴즈왕 찐천재 모집합니다\ud83c\udf93\\퀴즈 정답자에겐 기프트 카드...
55,없음,일반 고객,포인트 사용,최대 50% 페이백,없음 (페이백 이벤트),단 2일간,없음,포인트 사용하시고 페이백 받으세요!\\단 2일간! 최대 50% 페이백 받고 싶다면▶
56,없음,일반 고객,없음,최대 50% 페이백,없음,단 이틀간,없음,단/이/틀/간! 최대 5O% 페이백\\절반이나 돌려받기 가능! 딱 이틀 동안만 진행...
57,없음,장바구니 비울 분들,결제 시 포인트 사용,최대 50% 페이백,없음 (장바구니 상품에 따라 다름),단 이틀 동안,없음,곧 장바구니 비울 분들 주목☆\\쓴 만큼 돌려 받는 재미가 쏠쏠!\단 이/틀/동/안...
58,없음,일반 고객,포인트 사용 시,최대 반값까지 페이백,포인트 페이백,2일,없음,"포인트, 돌려 받고 싶지 않으세요?\\\ud83d\udea8단, 2일만! 포인트 사..."
59,"없음,","고객님,","포인트 사용,","최대 50%,","포인트 페이백,","단 이틀간,",없음,고객님은 소중하니깐 #포인트페이백\ud83d\udcb0\\단 이틀간! 최대 50%까...
60,없음,일반 고객,6번 이벤트 참여 후 1번 더 참여하기,없음,갤노트8,내일까지,없음,7주년★득템프 6번 찍으셨네요?\\내일까지! 1번만 더 찍으면 갤노트8의 행운이!
61,없음,득템프 참여자들,득템프 6개 달성 후 7주년 득템프 찍기,없음,갤노트8,D-1,없음,득템프 도장 쾅 찍고 갤노트8 받자♬\\D-1\u2757\u2757 지금까지 득템프...
62,없음,SNS 사용자,참여 인증 릴레이 완료,없음,갤노트8,내일까지,없음,#7주년 기념 #득템프 이벤트\\#SNS에 참여 인증 릴레이 중!\현재 득템프 6개...
63,없음,일반 고객,득템프 1회 참여,없음,갤노트8,내일까지 (단기간 이벤트),없음,딱 한 번만 더☝️ 찍어주세요!\\내.일.까.지 득템프 1회 더 꾸-욱\ud83d\...
64,없음,득템프 모으는 고객,7주년 득템프 6개 모으기,없음,갤럭시 노트8 당첨 기회,내일까지 (하루),없음,짝짝짝~ 득템프 많이 모으셨네요\ud83d\udc4f\\7주년 득템프를 6개나 모으...
65,없음,일반 고객 or 선물 고객,선물 구매 시,없음,메시지 카드 및 페이백 선물,없음,없음,말하지 않아도 알아요~\\메시지 카드로 내마음을 전할께♥ \(쉿! 분명 선물을 줬는...
66,없음,일반 고객,메시지 카드 보내기,없음,페이백 선물,없음,없음,페이백 쉽게 받는 법 공개!\\페이백 이벤트로 해결! 간편하게 메시지 카드만 보내고...
67,없음,소중한 사람에게 선물하는 고객,메시지카드+선물 보내기,없음,페이백 선물,없음,없음,마음도 전하고~ 페이백도 받고!\\소중한 사람에게 지금 바로 메시지카드+선물 보내면...
68,없음,일반 고객,메시지카드로 마음을 전할 경우,없음,페이백 선물,없음,없음,지금.. 내려옵니다..\\준 만큼 돌아오는 페이백 혜택이\메시지카드로 마음을 전하면...
69,없음,소중한 사람에게 메시지 카드를 보내는 고객,메시지 카드 전송,없음,페이백 선물,없음,새해,새해와 함께 찾아온 감동 모먼트\u2728\\메시지 카드로 소중한 마음 전해 주세요...
70,없음,일반 고객,주사위 던지기,없음(100% 포인트 당첨 혜택),발뮤다 공기청정기,없음,없음,주사위만 던져도 100% 포인트 당첨\\발뮤다 공기청정기 행운의 주인공은 누구\ud...
71,발뮤다,일반 고객,주사위 게임 참여,없음(포인트 증정),공기청정기,없음,미세먼지 시즌,주사위게임으로 공기청정기 획득하기♥\\주사위만 던져도 무/조/건 포인트 증정!\발뮤...
72,발뮤다,일반 고객,주사위 이벤트 참여,없음,공기청정기,없음,없음,요즘 모두가 탐내는 HOT템!\\【발뮤다 공기청정기】 득템할 행운의 주인공은 누구?...
73,발뮤다,일반 고객,주사위 던지기,없음,공기청정기,없음,없음,발뮤다 공기청정기 갖고 싶으신 분?\\누구나 가질 수 있는 \ud83d\udd25포...
74,없음,일반 고객,주사위 굴리기,없음,발뮤다 공기청정기,없음,없음,행운의 주인공이 되어주세요\ud83c\udf40\\주사위 굴리시면 발뮤다 공기청정기...
75,AIA,암보험 고객,암보험 상담,없음,1만원 혜택,없음,없음,암보험 보장금액은 충분한가요?\\AIA 암보험 상담받고 1만원 받으세요!~
76,AIA,암보험 보장 금액에 불만족한 고객,암보험 상담 받기,없음,1만원 혜택,없음,없음,지금 상담 받으면 1만원 즉시 증정!\\암보험 보장 금액에 불만족하셨다면? 지금 A...

In [31]:
path = '/content/drive/MyDrive/Advertising_By_Personality/data/train_polyglot2.json'

In [32]:
temp_dict = [{"marketing_entity": row['marketing_entity'].strip(), "marketing_target": row['marketing_target'].strip(), "benefit_conditions": row['benefit_conditions'].strip(), "discount_figure": row['discount_figure'].strip(), "promotional_items": row['promotional_items'].strip(), "event_period": row['event_period'].strip(), "season_information": row['season_information'].strip(), "label": row['label'].strip()} for _, row in data.iterrows()]

In [33]:
with open(path, 'w', encoding='utf-8') as f:
  for line in temp_dict:
    json_record = json.dumps(line, ensure_ascii=False)
    f.write(json_record + '\n')

##### 마케팅 정보 찾기

In [ ]:
text = "★올리브영=세일 천재★\\세일할 때마다 혜택은 UPGRADE⬆️\\이번에도 필수 뷰티템만 천재적 세일 특.가.로 제공 중(~12/5)"

In [ ]:
messages = [
    {"role": "system", "content": f"""'일요일에 데이트 어때~? [계절밥상] 소중한 사람과 함께 하는 통 돼지구이 FLEX! 만원 할인 쿠폰 받고 가요!'\n
                                      마케팅 주체: 계절밥상, 마케팅 대상: 주말 데이트, 할인: 만원 할인, 프로모션: 없음
                                      '짝짝짝! 친구 맺으면 1,000P~ 정답만 맞히면 포인트 주는 이벤트! 퀴즈 맞히고 1,000P 바로 받아가기'\n
                                      마케팅 주체: 없음, 마케팅 대상: 친구 맺기, 퀴즈 정답 맞히기, 할인: 없음, 프로모션: 1,000 포인트 제공
                                      음악 좋아하시는 분들 이거 다 알던데\\\\천재적인 드러머 [김태현 언택트 랜선콘서트] 지금 라방으로 진행 중★\\재즈&국악의 환상적 콜라보 만나보러 GO\n
                                      마케팅 주체: 없음, 마케팅 대상: 음악 좋아하시는 분들, 할인: 없음, 프로모션: 김태현 언택트 랜선콘서트"""},
    {"role": "user", "content": f"""{text}\n
                                    위 문장에서 마케팅 주체, 마케팅 대상, 할인, 프로모션 정보를 제외한 추가적인 마케팅 정보 3개 정도 더 알려줘"""}
]
result = generate_response(messages)
print(f"원본 : {text}")
print(result)

원본 : ★올리브영=세일 천재★\세일할 때마다 혜택은 UPGRADE⬆️\이번에도 필수 뷰티템만 천재적 세일 특.가.로 제공 중(~12/5)
1. 이벤트 기간: 12월 5일까지
2. 세일 품목: 필수 뷰티템
3. 혜택 등급: UPGRADE

마케팅 주체: 올리브영, 마케팅 대상: 뷰티 관련 상품 구매자, 할인: 천재적 세일 특가, 프로모션: 없음